import 15.2.0 Octopus source
Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/ceph/src/spdk/configure b/ceph/src/spdk/configure
--- a/ceph/src/spdk/configure
+++ b/ceph/src/spdk/configure
@@ -24,8 +24,9 @@ function usage()
 	echo " --enable-ubsan            Enable undefined behavior sanitizer"
 	echo " --enable-coverage         Enable code coverage tracking"
 	echo " --enable-lto              Enable link-time optimization"
+	echo " --enable-pgo-capture      Enable generation of profile guided optimization data"
+	echo " --enable-pgo-use          Use previously captured profile guided optimization data"
 	echo " --disable-tests           Disable building of tests"
-	echo " --with-env=path           Use an alternate environment implementation"
 	echo ""
 	echo "Specifying Dependencies:"
 	echo "--with-DEPENDENCY[=path]   Use the given dependency. Optionally, provide the"
@@ -34,22 +35,29 @@ function usage()
 	echo "                           disable features and components."
 	echo ""
 	echo "Valid dependencies are listed below."
-	echo " crypto                    Required to build vbdev crypto module."
-	echo "                           No path required."
 	echo " dpdk                      Optional.  Uses dpdk submodule in spdk tree if not specified."
 	echo "                           example: /usr/share/dpdk/x86_64-default-linuxapp-gcc"
+	echo " env                       Use an alternate environment implementation instead of DPDK."
+	echo "                           Implies --without-dpdk."
+	echo " igb-uio-driver            Build and use DPDK's igb-uio driver instead of uio_pci_generic"
+	echo "                           or vfio-pci. Required on some systems to use qat devices"
+	echo "                           No path required"
+	echo " crypto                    Required to build vbdev crypto module."
+	echo "                           No path required."
 	echo " fio                       Required to build fio_plugin."
 	echo "                           example: /usr/src/fio"
-	echo " igb-uio-driver            Required on some systems to use qat devices"
-	echo "                           No path required"
 	echo " vhost                     Required to build vhost target."
+	echo "                           No path required."
+	echo " internal-vhost-lib        Use the internal copy of rte_vhost."
 	echo "                           No path required."
 	echo " virtio                    Required to build vhost initiator (Virtio) bdev module."
 	echo "                           No path required."
 	echo " pmdk                      Required to build persistent memory bdev."
 	echo "                           example: /usr/share/pmdk"
+	echo " reduce                    Required to build vbdev compression module."
+	echo "                           No path required."
 	echo " vpp                       Required to build VPP net module."
-	echo "                           example: /vpp_repo/build-root/install-vpp-native/vpp"
+	echo "                           example: /vpp_repo/build-root/rpmbuild/vpp-18.01.1.0/build-root/install-vpp-native/vpp"
 	echo " rbd                       [disabled]"
 	echo "                           No path required."
 	echo " rdma                      [disabled]"
@@ -60,6 +68,16 @@ function usage()
 	echo "                           No path required."
 	echo " vtune                     Required to profile I/O under Intel VTune Amplifier XE."
 	echo "                           example: /opt/intel/vtune_amplifier_xe_version"
+	echo " ocf                       Required to build OCF module."
+	echo "                           If argument is directory, interpret it as root of OCF repo"
+	echo "                           If argument is file, interpret it as compiled OCF lib"
+	echo "                           If no argument is specified, OCF git submodule is used by default"
+	echo "                           example: /usr/src/ocf/"
+	echo " isal                      Enabled by default on x86 architecture. Can be built without though."
+	echo "                           No path required."
+	echo " uring                     Required to support I/O uring on Linux. If no argument, searches"
+	echo "                           the standard installation directory. If an argument is provided, it is"
+	echo "                           considered a directory containing liburing.a and io_uring.h."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -77,6 +95,7 @@ declare -A CONFIG
 source CONFIG.sh
 rm CONFIG.sh
 
+BUILD_CMD="${CC:-cc} -o /dev/null -x c $CPPFLAGS $CFLAGS $LDFLAGS"
 
 function check_dir() {
 	arg="$1"
@@ -138,6 +157,18 @@ for i in "$@"; do
 		--disable-lto)
 			CONFIG[LTO]=n
 			;;
+		--enable-pgo-capture)
+			CONFIG[PGO_CAPTURE]=y
+			;;
+		--disable-pgo-capture)
+			CONFIG[PGO_CAPTURE]=n
+			;;
+		--enable-pgo-use)
+			CONFIG[PGO_USE]=y
+			;;
+		--disable-pgo-use)
+			CONFIG[PGO_USE]=n
+			;;
 		--enable-tests)
 			CONFIG[TESTS]=y
 			;;
@@ -150,6 +181,13 @@ for i in "$@"; do
 		--disable-werror)
 			CONFIG[WERROR]=n
 			;;
+		--with-dpdk=*)
+			check_dir "$i"
+			CONFIG[DPDK_DIR]=$(readlink -f ${i#*=})
+			;;
+		--without-dpdk)
+			CONFIG[DPDK_DIR]=
+			;;
 		--with-env=*)
 			CONFIG[ENV]="${i#*=}"
 			;;
@@ -158,12 +196,6 @@ for i in "$@"; do
 			;;
 		--without-rbd)
 			CONFIG[RBD]=n
-			;;
-		--with-raid)
-			echo "--with-raid option ignored and is now deprecated.  RAID module is always enabled."
-			;;
-		--without-raid)
-			echo "--without-raid option ignored and is now deprecated.  RAID module is always enabled."
 			;;
 		--with-rdma)
 			CONFIG[RDMA]=y
@@ -183,13 +215,6 @@ for i in "$@"; do
 		--without-iscsi-initiator)
 			CONFIG[ISCSI_INITIATOR]=n
 			;;
-		--with-dpdk=*)
-			check_dir "$i"
-			CONFIG[DPDK_DIR]=$(readlink -f ${i#*=})
-			;;
-		--without-dpdk)
-			CONFIG[DPDK_DIR]=
-			;;
 		--with-crypto)
 			CONFIG[CRYPTO]=y
 			;;
@@ -201,6 +226,12 @@ for i in "$@"; do
 			;;
 		--without-vhost)
 			CONFIG[VHOST]=n
+			;;
+		--with-internal-vhost-lib)
+			CONFIG[VHOST_INTERNAL_LIB]=y
+			;;
+		--without-internal-vhost-lib)
+			CONFIG[VHOST_INTERNAL_LIB]=n
 			;;
 		--with-virtio)
 			CONFIG[VIRTIO]=y
@@ -219,6 +250,12 @@ for i in "$@"; do
 			;;
 		--without-pmdk)
 			CONFIG[PMDK]=n
+			;;
+		--with-reduce)
+			CONFIG[REDUCE]=y
+			;;
+		--without-reduce)
+			CONFIG[REDUCE]=n
 			;;
 		--with-vpp)
 			CONFIG[VPP]=y
@@ -255,6 +292,36 @@ for i in "$@"; do
 		--without-igb-uio-driver)
 			CONFIG[IGB_UIO_DRIVER]=n
 			;;
+		--with-ocf)
+			CONFIG[OCF]=y
+			CONFIG[OCF_PATH]=$(readlink -f "./ocf")
+			;;
+		--with-ocf=*)
+			CONFIG[OCF]=y
+			CONFIG[OCF_PATH]=$(readlink -f ${i#*=})
+			;;
+		--without-ocf)
+			CONFIG[OCF]=n
+			CONFIG[OCF_PATH]=
+			;;
+		--with-isal)
+			CONFIG[ISAL]=y
+			;;
+		--without-isal)
+			CONFIG[ISAL]=n
+			;;
+		--with-uring=*)
+			CONFIG[URING]=y
+			CONFIG[URING_PATH]=$(readlink -f ${i#*=})
+			;;
+		--with-uring)
+			CONFIG[URING]=y
+			CONFIG[URING_PATH]=
+			;;
+		--without-uring)
+			CONFIG[URING]=n
+			CONFIG[URING_PATH]=
+			;;
 		--)
 			break
 			;;
@@ -264,6 +331,18 @@ for i in "$@"; do
 			exit 1
 	esac
 done
+
+# Detect architecture and force no isal if non x86 archtecture
+arch=$(uname -m)
+if [[ $arch != x86_64* ]]; then
+	echo "Notice: ISAL auto-disabled due to CPU incompatiblity."
+	CONFIG[ISAL]=n
+fi
+
+if [[ "${CONFIG[ISAL]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+		echo "ERROR Conflicting options: --with-reduce is not compatible with --without-isal."
+		exit 1
+fi
 
 if [ -z "${CONFIG[ENV]}" ]; then
 	rootdir=$(readlink -f $(dirname $0))
@@ -279,8 +358,37 @@ if [ -z "${CONFIG[ENV]}" ]; then
 			CONFIG[DPDK_DIR]="${rootdir}/dpdk/build"
 			echo "Using default DPDK in ${CONFIG[DPDK_DIR]}"
 		fi
+
+		if [[ "${CONFIG[VHOST]}" = "y" ]] && [[ "${CONFIG[VHOST_INTERNAL_LIB]}" = "n" ]]; then
+			# We lookup "common_linux" file to check if DPDK version is >= 19.05.
+			# "common_linux" is available since exactly DPDK 19.05 - it was renamed
+			# from "common_linuxapp".
+			if [ ! -f "$rootdir"/dpdk/config/common_linux ]; then
+				echo "Notice: Using internal, legacy rte_vhost library due to DPDK" \
+				     "version < 19.05"
+				CONFIG[VHOST_INTERNAL_LIB]=y
+			fi
+		fi
+	else
+		if [[ "${CONFIG[VHOST]}" = "y" ]] && [[ "${CONFIG[VHOST_INTERNAL_LIB]}" = "n" ]]; then
+			# DPDK must be already built, so we can simply try to use the new rte_vhost.
+			# It has a number of internal dependencies though, so don't try to link the
+			# program, just compile it
+			if ! echo -e '#include <rte_vhost.h>\n' \
+				'int main(void) { return rte_vhost_extern_callback_register(0, NULL, NULL); }\n' \
+				| $BUILD_CMD -c -Wno-deprecated-declarations -I"${CONFIG[DPDK_DIR]}/include" -; then
+				echo "Notice: DPDK's rte_vhost not found or version < 19.05, using internal," \
+				     "legacy rte_vhost library."
+				CONFIG[VHOST_INTERNAL_LIB]=y
+			fi
+		fi
 	fi
 else
+	if [ -n "${CONFIG[DPDK_DIR]}" ]; then
+		echo "--with-env and --with-dpdk are mutually exclusive."
+		exit 1
+	fi
+
 	if [ "${CONFIG[VHOST]}" = "y" ]; then
 		echo "Vhost is only supported when using the default DPDK environment. Disabling it."
 	fi
@@ -323,19 +431,21 @@ if [[ "$OSTYPE" == "freebsd"* ]]; then
 fi
 
 if [ "${CONFIG[RDMA]}" = "y" ]; then
-	if [ "$OSTYPE" != "FreeBSD"* ]; then
-		ibv_lib_file="$(readlink -f /usr/lib64/libibverbs.so)" || true
-		if [ -z $ibv_lib_file ]; then
-			ibv_lib_file="libibverbs.so.0.0.0"
-		fi
-		ibv_ver_str="$(basename $ibv_lib_file)"
-		ibv_maj_ver=`echo $ibv_ver_str | cut -d. -f3`
-		ibv_min_ver=`echo $ibv_ver_str | cut -d. -f4`
-		if [[ "$ibv_maj_var" > 1 || ("$ibv_maj_ver" -eq 1 && "$ibv_min_ver" -ge 1) ]]; then
-			CONFIG[RDMA_SEND_WITH_INVAL]="y"
-		else
-			CONFIG[RDMA_SEND_WITH_INVAL]="n"
-			echo "
+	if ! echo -e '#include <infiniband/verbs.h>\n#include <rdma/rdma_verbs.h>\n' \
+		'int main(void) { return 0; }\n' \
+		| $BUILD_CMD -libverbs -lrdmacm - 2>/dev/null; then
+		echo --with-rdma requires libverbs and librdmacm.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+
+	if echo -e '#include <infiniband/verbs.h>\n' \
+		'int main(void) { return !!IBV_WR_SEND_WITH_INV; }\n' \
+		| $BUILD_CMD -c - 2>/dev/null; then
+		CONFIG[RDMA_SEND_WITH_INVAL]="y"
+	else
+		CONFIG[RDMA_SEND_WITH_INVAL]="n"
+		echo "
 *******************************************************************************
 WARNING: The Infiniband Verbs opcode Send With Invalidate is either not
 supported or is not functional with the current version of libibverbs installed
@@ -349,19 +459,152 @@ be unable to leverage that operation using the currently installed version
 of libibverbs, so Linux kernel NVMe-oF initiators based on kernels greater
 than or equal to 4.14 will see significantly reduced performance.
 *******************************************************************************"
+	fi
+fi
+
+if [[ "${CONFIG[ISAL]}" = "y" ]] || [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
+	ver=$(nasm -v | awk '{print $3}' | sed 's/[^0-9]*//g')
+	if [[ "${ver:0:1}" -le "2" ]] && [[ "${ver:0:3}" -le "213" ]] && [[ "${ver:0:5}" -lt "21303" ]]; then
+		echo "Notice: ISA-L, compression & crypto auto-disabled due to nasm dependency."
+		echo "These features require NASM version 2.13.03 or newer.  Please install"
+		echo "or upgrade then re-run this script."
+		CONFIG[ISAL]=n
+		CONFIG[CRYPTO]=n
+		CONFIG[IPSEC_MB]=n
+		CONFIG[REDUCE]=n
+	else
+		if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
+			CONFIG[IPSEC_MB]=y
 		fi
 	fi
 fi
 
-if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
-	if [[ $(nasm -v | sed 's/[^0-9]*//g' | awk '{print substr ($0, 0, 5)}') -lt "21202" ]]; then
-		echo Crypto requires NASM version 2.12.02 or newer.  Please install
-		echo or upgrade then re-run this script.
+if [[ "${CONFIG[ISAL]}" = "y" ]]; then
+	if [ ! -f "$rootdir"/isa-l/autogen.sh ]; then
+		echo "ISA-L was not found; To install ISA-L run:"
+		echo "  git submodule update --init"
 		exit 1
-        else
-		if [[ "$(find /usr -name intel-ipsec-mb.h 2>/dev/null)" == "" ]]; then
-			echo "To enable crypto you must first go to the intel-ipsec-mb directory and "
-			echo "run 'make' then 'sudo make install' then re-run this script."
+	fi
+
+	if [[ "${CONFIG[RBD]}" = "y" ]]; then
+		echo "ISAL and RBD cannot co-exist currently so disabling ISAL and compression."
+		CONFIG[ISAL]=n
+		CONFIG[REDUCE]=n
+	else
+		cd $rootdir/isa-l
+		ISAL_LOG=/tmp/spdk-isal.log
+		echo -n "Configuring ISA-L (logfile: $ISAL_LOG)..."
+		./autogen.sh &> $ISAL_LOG
+		./configure CFLAGS="-fPIC -g -O2" --enable-shared=no >> $ISAL_LOG 2>&1
+		echo "done."
+		cd $rootdir
+	fi
+fi
+
+if [[ "${CONFIG[PMDK]}" = "y" ]]; then
+	if ! echo -e '#include <libpmemblk.h>\nint main(void) { return 0; }\n' \
+		| $BUILD_CMD -lpmemblk - 2>/dev/null; then
+		echo --with-pmdk requires libpmemblk.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+	if ! echo -e '#include <libpmem.h>\nint main(void) { return 0; }\n' \
+		| $BUILD_CMD -lpmem - 2>/dev/null; then
+		echo --with-reduce requires libpmem.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[RBD]}" = "y" ]]; then
+	if ! echo -e '#include <rbd/librbd.h>\n#include <rados/librados.h>\n' \
+		'int main(void) { return 0; }\n' \
+		| $BUILD_CMD -lrados -lrbd - 2>/dev/null; then
+		echo --with-rbd requires librados and librbd.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[ISCSI_INITIATOR]}" = "y" ]]; then
+	# Fedora installs libiscsi to /usr/lib64/iscsi for some reason.
+	if ! echo -e '#include <iscsi/iscsi.h>\n#include <iscsi/scsi-lowlevel.h>\n' \
+		'#if LIBISCSI_API_VERSION < 20150621\n' \
+		'#error\n' \
+		'#endif\n' \
+		'int main(void) { return 0; }\n' \
+		| $BUILD_CMD -L/usr/lib64/iscsi -liscsi - 2>/dev/null; then
+		echo --with-iscsi-initiator requires libiscsi with
+		echo 'LIBISCSI_API_VERSION >= 20150621.'
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[LOG_BACKTRACE]}" = "y" ]]; then
+	if ! echo -e '#include <libunwind.h>\nint main(void) { return 0; }\n' \
+		| $BUILD_CMD -lunwind - 2>/dev/null; then
+		echo --enable-log-bt requires libunwind.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[ASAN]}" = "y" ]]; then
+	if ! echo -e 'int main(void) { return 0; }\n' \
+		| $BUILD_CMD -fsanitize=address - 2>/dev/null; then
+		echo --enable-asan requires libasan.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[UBSAN]}" = "y" ]]; then
+	if ! echo -e 'int main(void) { return 0; }\n' \
+		| $BUILD_CMD -fsanitize=undefined - 2>/dev/null; then
+		echo --enable-ubsan requires libubsan.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[TSAN]}" = "y" ]]; then
+	if ! echo -e 'int main(void) { return 0; }\n' \
+		| $BUILD_CMD -fsanitize=thread - 2>/dev/null; then
+		echo --enable-tsan requires libtsan.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[OCF]}" = "y" ]]; then
+	# If OCF_PATH is a file, assume it is a library and use it to compile with
+	if [ -f ${CONFIG[OCF_PATH]} ]; then
+		CONFIG[CUSTOMOCF]=y
+	else
+		CONFIG[CUSTOMOCF]=n
+	fi
+fi
+
+if [[ "${CONFIG[PGO_CAPTURE]}" = "y" && "${CONFIG[PGO_USE]}" = "y" ]]; then
+	echo "ERROR: --enable-pgo-capture and --enable-pgo-use are mutually exclusive."
+	exit 1
+elif [[ "${CONFIG[PGO_USE]}" = "y" ]]; then
+	CC_TYPE=$($rootdir/scripts/detect_cc.sh --cc=$CC --cxx=$CXX --lto=$CONFIG[LTO] --ld=$LD | grep "CC_TYPE" | cut -d "=" -f 2)
+	if [[ "$CC_TYPE" = "clang" ]]; then
+		# For clang we need to run an extra step on gathered profiling data.
+		echo "Generating suitable profile data"
+		llvm-profdata merge -output=build/pgo/default.profdata build/pgo
+	fi
+fi
+
+if [[ "${CONFIG[URING]}" = "y" ]]; then
+	if [[ -n "${CONFIG[URING_PATH]}" ]]; then
+		if [ ! -d "${CONFIG[URING_PATH]}" ]; then
+			echo "${CONFIG[URING_PATH]}: directory not found"
 			exit 1
 		fi
 	fi
@@ -386,13 +629,15 @@ for key in ${!CONFIG[@]}; do
 done
 # On FreeBSD sed -i 'SUFFIX' - SUFFIX is mandatory. So no way but to delete the backed file.
 rm -f mk/config.mk.bak
+echo "done."
 
 # Environment variables
-[ -n "$CFLAGS" ] && echo "CFLAGS?=$CFLAGS" >> mk/config.mk
-[ -n "$CXXFLAGS" ] && echo "CXXFLAGS?=$CXXFLAGS" >> mk/config.mk
-[ -n "$LDFLAGS" ] && echo "LDFLAGS?=$LDFLAGS" >> mk/config.mk
-[ -n "$DESTDIR" ] && echo "DESTDIR?=$DESTDIR" >> mk/config.mk
-
+echo -n "Creating mk/cc.flags.mk..."
+rm -f mk/cc.flags.mk
+[ -n "$CFLAGS" ] && echo "CFLAGS?=$CFLAGS" > mk/cc.flags.mk
+[ -n "$CXXFLAGS" ] && echo "CXXFLAGS?=$CXXFLAGS" >> mk/cc.flags.mk
+[ -n "$LDFLAGS" ] && echo "LDFLAGS?=$LDFLAGS" >> mk/cc.flags.mk
+[ -n "$DESTDIR" ] && echo "DESTDIR?=$DESTDIR" >> mk/cc.flags.mk
 echo "done."
 
 if [[ "$OSTYPE" == "freebsd"* ]]; then
