import source of ceph Tentacle 20.2.1
Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/ceph/src/nvmeof/gateway/Makefile b/ceph/src/nvmeof/gateway/Makefile
--- a/ceph/src/nvmeof/gateway/Makefile
+++ b/ceph/src/nvmeof/gateway/Makefile
@@ -1,11 +1,28 @@
 # Make config
 MAKEFLAGS += --no-builtin-rules --no-builtin-variables
+TARGET_ARCH := $(shell uname -m)
 .SUFFIXES:
 
-# Includes
+# Assign default CPU arch related parameters
 include .env
+ifneq (, $(filter $(TARGET_ARCH), arm64 aarch64))
+ceph_repo_arch = arm64
+TARGET_PLATFORM = linux/arm64
+SPDK_TARGET_ARCH = armv8-a+crypto
+SPDK_MAKEFLAGS = $(shell echo "DPDKBUILD_FLAGS=-Dplatform=generic -j $$(nproc)")
+else ifneq (, $(filter $(TARGET_ARCH), amd64 x86_64))
+ceph_repo_arch = x86_64
+TARGET_PLATFORM = linux/amd64
+SPDK_TARGET_ARCH = x86-64-v2
+else
+$(error Unspported CPU arch '$(TARGET_ARCH)' !! Set TARGET_ARCH to x86_64, amd64 or arm64, aarch64 arches)
+endif
+
+# Includes
 include mk/containerized.mk
 include mk/demo.mk
+include mk/demosecurepsk.mk
+include mk/demosecuredhchap.mk
 include mk/misc.mk
 include mk/autohelp.mk
 
@@ -13,17 +30,22 @@ include mk/autohelp.mk
 .DEFAULT_GOAL := all
 all: setup $(ALL)
 
+verify: ## Run Python source files through flake8
+	@echo Verifying Python source files
+	flake8 control/*.py tests/*.py
+
 setup: ## Configure huge-pages (requires sudo/root password)
 
 	@echo Setup core dump pattern as /tmp/coredump/core.*
 	mkdir -p /tmp/coredump
 	sudo mkdir -p /var/log/ceph
+	sudo chmod 0755 /var/log/ceph
 	sudo bash -c 'echo "|/usr/bin/env tee /tmp/coredump/core.%e.%p.%h.%t" > /proc/sys/kernel/core_pattern'
 	sudo bash -c 'echo $(HUGEPAGES) > $(HUGEPAGES_DIR)'
 	@echo Actual Hugepages allocation: $$(cat $(HUGEPAGES_DIR))
 	@[ $$(cat $(HUGEPAGES_DIR)) -eq $(HUGEPAGES) ]
 
-build pull logs: SVC ?= ceph spdk bdevperf nvmeof nvmeof-devel nvmeof-cli discovery
+build pull logs down: SVC ?= ceph spdk bdevperf nvmeof nvmeof-devel nvmeof-cli discovery
 
 build: export NVMEOF_GIT_REPO != git remote get-url origin
 build: export NVMEOF_GIT_BRANCH != git name-rev --name-only HEAD
@@ -33,15 +55,40 @@ build: export SPDK_GIT_BRANCH != git -C spdk name-rev --name-only HEAD
 build: export SPDK_GIT_COMMIT != git rev-parse HEAD:spdk
 build: export BUILD_DATE != date -u +"%Y-%m-%d %H:%M:%S %Z"
 build: export NVMEOF_GIT_MODIFIED_FILES != git status -s | grep -e "^ *M" | sed 's/^ *M //' | xargs
-build: export CEPH_CLUSTER_CEPH_REPO_BASEURL != curl -s https://shaman.ceph.com/api/repos/ceph/$(CEPH_BRANCH)/$(CEPH_SHA)/centos/9/ | jq -r '.[0].url'
 
+# Variables
+SHAMAN_FETCH_ATTEMPTS := 3
+
+# Fetch and export CEPH_CLUSTER_CEPH_REPO_BASEURL with retries
+build: export CEPH_CLUSTER_CEPH_REPO_BASEURL != \
+	for i in $$(seq 1 $(SHAMAN_FETCH_ATTEMPTS)); do \
+		>&2 echo "Attempt ($$i): Fetching URL for arch=$(ceph_repo_arch), branch=$(CEPH_BRANCH), sha=$(CEPH_SHA)..."; \
+		url=$$(curl -s https://shaman.ceph.com/api/repos/ceph/$(CEPH_BRANCH)/$(CEPH_SHA)/centos/9/ | jq -r '.[] | select(.status == "ready" and .archs[] == "$(ceph_repo_arch)") | .url'); \
+		if [ -n "$$url" ]; then \
+			>&2 echo "Success: Retrieved URL for arch=$(ceph_repo_arch), branch=$(CEPH_BRANCH), sha=$(CEPH_SHA): $$url"; \
+			echo "$$url"; \
+			break; \
+		fi; \
+		>&2 echo "Retrying... Failed attempt ($$i) for arch=$(ceph_repo_arch), branch=$(CEPH_BRANCH), sha=$(CEPH_SHA)"; \
+		sleep 2; \
+	done; \
+	if [ -z "$$url" ]; then \
+		>&2 echo "Failure: Unable to retrieve a valid URL for arch=$(ceph_repo_arch), branch=$(CEPH_BRANCH), sha=$(CEPH_SHA) after $(SHAMAN_FETCH_ATTEMPTS) attempts"; \
+		exit 1; \
+	fi
+
+build: export TARGET_PLATFORM := $(TARGET_PLATFORM)
+build: export SPDK_TARGET_ARCH := $(SPDK_TARGET_ARCH)
+build: export SPDK_MAKEFLAGS := $(SPDK_MAKEFLAGS)
 up: ## Launch services
-up: SVC ?= ceph nvmeof ## Services
-up: OPTS ?= --abort-on-container-exit --exit-code-from $(SVC) --remove-orphans
-#up: override OPTS += --scale nvmeof=$(SCALE)
+up: SCALE?= 1 ## Number of gateways
+up:
+	@$(CURDIR)/tests/ha/start_up.sh $(SCALE)
 
 clean: $(CLEAN) setup  ## Clean-up environment
 clean: override HUGEPAGES = 0
+clean:
+	/usr/bin/rm -f control/proto/gateway_pb2_grpc.py control/proto/gateway_pb2.py control/proto/gateway_pb2.pyi control/proto/monitor_pb2_grpc.py control/proto/monitor_pb2.py control/proto/monitor_pb2.pyi
 
 update-lockfile: run ## Update dependencies in lockfile (pdm.lock)
 update-lockfile: SVC=nvmeof-builder-base
diff --git a/ceph/src/nvmeof/gateway/spdk/configure b/ceph/src/nvmeof/gateway/spdk/configure
--- a/ceph/src/nvmeof/gateway/spdk/configure
+++ b/ceph/src/nvmeof/gateway/spdk/configure
@@ -28,15 +28,20 @@ function usage() {
 	echo " --cross-prefix=prefix     Prefix for cross compilation (default: none)"
 	echo "                           example: aarch64-linux-gnu"
 	echo " --libdir=path             Configure installation path for the libraries (default: \$prefix/lib)"
-	echo ""
+	echo " --max-lcores=VAL          DPDK configuration. VAL defines maximum number of lcores supported"
+	echo "                           by EAL, or enables autodetection if set to 'detect'. When 'detect'"
+	echo "                           is specified, DPDK will detect number of cores in the system during"
+	echo "                           compilation, and will set maximum number of lcores to this value"
+	echo " --max-numa-nodes=VAL      VAL defines maximum number of NUMA nodes supported for iobuf"
+	echo "                           buffer pools."
 	echo " --enable-debug            Configure for debug builds"
 	echo " --enable-werror           Treat compiler warnings as errors"
 	echo " --enable-asan             Enable address sanitizer"
 	echo " --enable-ubsan            Enable undefined behavior sanitizer"
 	echo " --enable-coverage         Enable code coverage tracking"
 	echo " --enable-lto              Enable link-time optimization"
-	echo " --enable-pgo-capture      Enable generation of profile guided optimization data"
-	echo " --enable-pgo-use          Use previously captured profile guided optimization data"
+	echo " --enable-pgo-capture[=PATH]      Enable generation of profile guided optimization data"
+	echo " --enable-pgo-use[=PATH]   Use previously captured profile guided optimization data"
 	echo " --enable-cet              Enable Intel Control-flow Enforcement Technology (CET)"
 	echo " --disable-tests           Disable building of functional tests"
 	echo " --disable-unit-tests      Disable building of unit tests"
@@ -71,9 +76,6 @@ function usage() {
 	echo "                           vfio-user initiator is always built-in in Linux."
 	echo "                           example: /usr/src/libvfio-user"
 	echo " --without-vfio-user       No path required."
-	echo " --with-pmdk[=DIR]         Build persistent memory bdev. (Deprecated)
-					 example: /usr/share/pmdk"
-	echo " --without-pmdk		 No path required."
 	echo " --with-vbdev-compress     Build vbdev compression module and dependencies."
 	echo " --without-vbdev-compress  No path required."
 	echo " --with-dpdk-compressdev   Build accel DPDK compression module and dependencies."
@@ -82,7 +84,7 @@ function usage() {
 	echo " --without-rbd             No path required."
 	echo " --with-ublk               Build ublk library."
 	echo " --without-ublk            No path required."
-	echo " --with-rdma[=DIR]         Build RDMA transport for NVMf target and initiator."
+	echo " --with-rdma[=PROVIDER]    Build RDMA transport for NVMf target and initiator."
 	echo " --without-rdma            Accepts optional RDMA provider name. Can be \"verbs\" or \"mlx5_dv\"."
 	echo "                           If no provider specified, \"verbs\" provider is used by default."
 	echo " --with-fc[=DIR]           Build FC transport for NVMf target."
@@ -95,9 +97,10 @@ function usage() {
 	echo " --without-shared          No path required."
 	echo " --with-iscsi-initiator    Build with iscsi bdev module."
 	echo " --without-iscsi-initiator No path required."
-	echo " --with-vtune=DIR          Required to profile I/O under Intel VTune Amplifier XE. (Deprecated)"
-	echo " --without-vtune           example: /opt/intel/vtune_amplifier_xe_version"
-	echo " --with-ocf[=DIR]          Build OCF library and bdev module. (Deprecated)"
+	echo " --with-vtune=DIR          Required to profile I/O under Intel VTune Profiler."
+	echo "                           example: /opt/intel/oneapi/vtune/version"
+	echo " --without-vtune           Support for Intel VTune Profiler will not be provided."
+	echo " --with-ocf[=DIR]          Build OCF library and bdev module."
 	echo " --without-ocf             If argument is directory, interpret it as root of OCF repo"
 	echo "                           If argument is file, interpret it as compiled OCF lib"
 	echo "                           If no argument is specified, OCF git submodule is used by default"
@@ -106,6 +109,8 @@ function usage() {
 	echo " --without-uring           If an argument is provided, it is considered a directory containing"
 	echo "                           liburing.a and io_uring.h. Otherwise the regular system paths will"
 	echo "                           be searched."
+	echo " --with-dpdk-uadk          Build uadk DPDK module. No path required."
+	echo " --without-dpdk-uadk       Disable uadk DPDK module."
 	echo " --without-uring-zns       Build I/O uring module without ZNS (zoned namespaces) support."
 	echo " --with-openssl[=DIR]      Build OPENSSL with custom path. Otherwise the regular system paths will"
 	echo "                           be searched."
@@ -127,6 +132,10 @@ function usage() {
 	echo " --without-sma             No path required."
 	echo " --with-avahi              Build with Avahi mDNS discovery client service enabled in bdev-nvme module."
 	echo " --without-avahi           No path required."
+	echo " --with-golang             Build with components written in Go"
+	echo " --without-golang          No path required."
+	echo " --with-aio-fsdev          Build aio FSDEV component."
+	echo " --without-aio-fsdev       No path required."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -167,8 +176,9 @@ done
 # Detect the compiler toolchain
 $rootdir/scripts/detect_cc.sh --cc="$CC" --cxx="$CXX" --lto="${CONFIG[LTO]}" --ld="$LD" --cross-prefix="${CONFIG[CROSS_PREFIX]}" > $rootdir/mk/cc.mk
 
-CC=$(grep "DEFAULT_CC=" "$rootdir/mk/cc.mk" | sed s/DEFAULT_CC=//)
-CC_TYPE=$(grep "CC_TYPE=" "$rootdir/mk/cc.mk" | cut -d "=" -f 2)
+mapfile -t cc < <(grep "=" "$rootdir/mk/cc.mk")
+source <(printf '%q\n' "${cc[@]}")
+CC=$DEFAULT_CC
 
 arch=$($CC -dumpmachine)
 sys_name=$(uname -s)
@@ -181,7 +191,9 @@ if [[ $sys_name != "Linux" ]]; then
 	# Vhost, rte_vhost library and virtio are only supported on Linux.
 	CONFIG[VHOST]="n"
 	CONFIG[VIRTIO]="n"
-	echo "Notice: Vhost, rte_vhost library and virtio are only supported on Linux. Turning off default feature."
+	CONFIG[NVME_CUSE]="n"
+	echo "Notice: Vhost, rte_vhost library, virtio, and fuse"
+	echo "are only supported on Linux. Turning off default feature."
 fi
 
 function check_dir() {
@@ -331,11 +343,19 @@ for i in "$@"; do
 		--enable-pgo-capture)
 			CONFIG[PGO_CAPTURE]=y
 			;;
+		--enable-pgo-capture=*)
+			CONFIG[PGO_CAPTURE]=y
+			CONFIG[PGO_DIR]="${i#*=}"
+			;;
 		--disable-pgo-capture)
 			CONFIG[PGO_CAPTURE]=n
 			;;
 		--enable-pgo-use)
 			CONFIG[PGO_USE]=y
+			;;
+		--enable-pgo-use=*)
+			CONFIG[PGO_USE]=y
+			CONFIG[PGO_DIR]="${i#*=}"
 			;;
 		--disable-pgo-use)
 			CONFIG[PGO_USE]=n
@@ -503,6 +523,12 @@ for i in "$@"; do
 		--without-crypto)
 			CONFIG[CRYPTO]=n
 			;;
+		--with-dpdk-uadk)
+			CONFIG[DPDK_UADK]=y
+			;;
+		--without-dpdk-uadk)
+			CONFIG[DPDK_UADK]=n
+			;;
 		--with-vhost)
 			CONFIG[VHOST]=y
 			;;
@@ -526,18 +552,6 @@ for i in "$@"; do
 			;;
 		--without-vfio-user)
 			CONFIG[VFIO_USER]=n
-			;;
-		--with-pmdk)
-			CONFIG[PMDK]=y
-			CONFIG[PMDK_DIR]=""
-			;;
-		--with-pmdk=*)
-			CONFIG[PMDK]=y
-			check_dir "$i"
-			CONFIG[PMDK_DIR]=$(readlink -f ${i#*=})
-			;;
-		--without-pmdk)
-			CONFIG[PMDK]=n
 			;;
 		--with-vbdev-compress)
 			CONFIG[VBDEV_COMPRESS]=y
@@ -666,6 +680,37 @@ for i in "$@"; do
 		--without-avahi)
 			CONFIG[AVAHI]=n
 			;;
+		--with-golang)
+			CONFIG[GOLANG]=y
+			;;
+		--without-golang)
+			CONFIG[GOLANG]=n
+			;;
+		--max-lcores='')
+			echo "Must specify max number of lcores for --max-lcores"
+			usage
+			exit 1
+			;;
+		--max-lcores=*)
+			CONFIG[MAX_LCORES]="${i#*=}"
+			CONFIG["MAX_LCORES"]=${CONFIG["MAX_LCORES"],,}
+			;;
+		--max-numa-nodes='')
+			echo "Must specify max number of nodes for --max-numa-nodes"
+			usage
+			exit 1
+			;;
+		--max-numa-nodes=*)
+			CONFIG[MAX_NUMA_NODES]="${i#*=}"
+			CONFIG["MAX_NUMA_NODES"]=${CONFIG["MAX_NUMA_NODES"],,}
+			;;
+		--with-aio-fsdev)
+			CONFIG[AIO_FSDEV]=y
+			AIO_FSDEV_REQUIRED=y
+			;;
+		--without-aio-fsdev)
+			CONFIG[AIO_FSDEV]=n
+			;;
 		--)
 			break
 			;;
@@ -683,6 +728,10 @@ else
 	BUILD_CMD=($CC -o /dev/null -x c $CPPFLAGS $CFLAGS $LDFLAGS)
 fi
 BUILD_CMD+=(-I/usr/local/include -L/usr/local/lib)
+BUILD_CMD+=("-fuse-ld=$LD_TYPE")
+if [[ -n "${CONFIG[OPENSSL_PATH]}" ]]; then
+	BUILD_CMD+=("-I${CONFIG[OPENSSL_PATH]}/include" "-L${CONFIG[OPENSSL_PATH]}")
+fi
 
 if [[ "${CONFIG[VFIO_USER]}" = "y" ]]; then
 	if ! echo -e '#include <json-c/json.h>' \
@@ -709,8 +758,7 @@ if [[ "${CONFIG[IDXD]}" = "y" ]]; then
 		cpu_vendor=$(grep -i 'vendor' /proc/cpuinfo --max-count=1)
 	fi
 	if [[ "$cpu_vendor" != *"$intel"* ]]; then
-		echo "ERROR: IDXD cannot be used due to CPU incompatibility."
-		exit 1
+		echo "WARNING: IDXD cannot be used due to CPU incompatibility."
 	fi
 	if [ -e /usr/include/accel-config/libaccel_config.h ]; then
 		CONFIG[IDXD_KERNEL]=y
@@ -781,7 +829,6 @@ else
 fi
 
 if [ "${CONFIG[VTUNE]}" = "y" ]; then
-	echo "WARNING: VTune support is deprecated."
 	if [ -z "${CONFIG[VTUNE_DIR]}" ]; then
 		echo "When VTune is enabled, you must specify the VTune directory using --with-vtune=path"
 		exit 1
@@ -800,10 +847,7 @@ fi
 
 if [[ $sys_name == "FreeBSD" ]]; then
 	# FreeBSD doesn't support all configurations
-	if [[ "${CONFIG[COVERAGE]}" == "y" ]]; then
-		echo "ERROR: CONFIG_COVERAGE not available on FreeBSD"
-		exit 1
-	fi
+	CONFIG[FSDEV]=n
 fi
 
 if [[ $sys_name == "Linux" ]]; then
@@ -906,17 +950,6 @@ if [[ "${CONFIG[FC]}" = "y" ]]; then
 	fi
 fi
 
-if [[ "${CONFIG[PMDK]}" = "y" ]]; then
-	echo "WARNING: PMDK - bdev_pmem is deprecated."
-	echo "WARNING: PMDK - ACCEL_FLAG_PERSISTENT in accel_sw module is deprecated."
-	if ! echo -e '#include <libpmemblk.h>\nint main(void) { return 0; }\n' \
-		| "${BUILD_CMD[@]}" -lpmemblk - 2> /dev/null; then
-		echo "--with-pmdk requires libpmemblk."
-		echo "Please install then re-run this script."
-		exit 1
-	fi
-fi
-
 function dpdk_version() {
 	# Check DPDK version to determine if mlx5_pci driver is supported
 	local dpdk_ver="none"
@@ -943,7 +976,6 @@ function mlx5_build() {
 }
 
 if [[ "${CONFIG[VBDEV_COMPRESS]}" = "y" ]]; then
-	echo "WARNING: PMDK - Persistent device support with bdev_compress is deprecated."
 	if ! echo -e '#include <libpmem.h>\nint main(void) { return 0; }\n' \
 		| "${BUILD_CMD[@]}" -lpmem - 2> /dev/null; then
 		echo "--with-vbdev-compress requires libpmem."
@@ -1020,7 +1052,7 @@ fi
 if [[ "${CONFIG[NVME_CUSE]}" = "y" ]]; then
 	if ! echo -e '#define FUSE_USE_VERSION 31\n#include <fuse3/cuse_lowlevel.h>\n#include <fuse3/fuse_lowlevel.h>\n#include <fuse3/fuse_opt.h>\nint main(void) { return 0; }\n' \
 		| "${BUILD_CMD[@]}" -lfuse3 -D_FILE_OFFSET_BITS=64 - 2> /dev/null; then
-		echo "--with-cuse requires libfuse3."
+		echo "--with-nvme-cuse requires libfuse3."
 		echo "Please install then re-run this script."
 		exit 1
 	fi
@@ -1041,6 +1073,14 @@ if [[ "${CONFIG[UBLK]}" = "y" ]]; then
 		'int main(void) { return 0; }\n' \
 		| "${BUILD_CMD[@]}" -luring - 2> /dev/null; then
 		echo "--with-ublk requires liburing and ublk_drv."
+		echo "Please install then re-run this script."
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[DPDK_UADK]}" = "y" ]]; then
+	if ! pkg-config --exists libwd; then
+		echo "--with-dpdk-uadk requires uadk library."
 		echo "Please install then re-run this script."
 		exit 1
 	fi
@@ -1109,8 +1149,31 @@ if echo -e '#include <stdlib.h>\nint main(void) { arc4random(); return 0; }\n' \
 	CONFIG[HAVE_ARC4RANDOM]="y"
 fi
 
+if echo -e '#include <uuid/uuid.h>\nint main(void) { uuid_generate_sha1(NULL, NULL, NULL, 0); return 0; }\n' \
+	| "${BUILD_CMD[@]}" - -luuid 2> /dev/null; then
+	CONFIG[HAVE_UUID_GENERATE_SHA1]="y"
+fi
+
+if echo -e '#include <execinfo.h>' | "${BUILD_CMD[@]}" -c - 2> /dev/null; then
+	CONFIG[HAVE_EXECINFO_H]=y
+fi
+
+if echo -e '#include <keyutils.h>\nint main(void) { request_key(0, 0, 0, -1); return 0; }' \
+	| "${BUILD_CMD[@]}" - -lkeyutils 2> /dev/null; then
+	CONFIG[HAVE_KEYUTILS]=y
+fi
+
+if echo -e '#include <openssl/evp.h>\nint main(void) { EVP_MAC *m = EVP_MAC_fetch(0, 0, 0); return 0; }' \
+	| "${BUILD_CMD[@]}" - -lcrypto 2> /dev/null; then
+	CONFIG[HAVE_EVP_MAC]=y
+fi
+
+if echo -e '#include <lz4.h>\nint main(void) { return 0; }\n' \
+	| "${BUILD_CMD[@]}" -llz4 - 2> /dev/null; then
+	CONFIG[HAVE_LZ4]="y"
+fi
+
 if [[ "${CONFIG[OCF]}" = "y" ]]; then
-	echo "WARNING: OCF - bdev_ocf is deprecated."
 	# If OCF_PATH is a file, assume it is a library and use it to compile with
 	if [ -f ${CONFIG[OCF_PATH]} ]; then
 		CONFIG[CUSTOMOCF]=y
@@ -1122,11 +1185,17 @@ fi
 if [[ "${CONFIG[PGO_CAPTURE]}" = "y" && "${CONFIG[PGO_USE]}" = "y" ]]; then
 	echo "ERROR: --enable-pgo-capture and --enable-pgo-use are mutually exclusive."
 	exit 1
-elif [[ "${CONFIG[PGO_USE]}" = "y" ]]; then
+elif [[ "${CONFIG[PGO_CAPTURE]}" = "y" || "${CONFI[PGO_USE]}" = "y" ]]; then
+	if [[ -z "${CONFIG[PGO_DIR]}" ]]; then
+		CONFIG[PGO_DIR]=$(realpath $rootdir/build/pgo)
+	fi
+fi
+
+if [[ "${CONFIG[PGO_USE]}" = "y" ]]; then
 	if [[ "$CC_TYPE" = "clang" ]]; then
 		# For clang we need to run an extra step on gathered profiling data.
 		echo "Generating suitable profile data"
-		llvm-profdata merge -output=build/pgo/default.profdata build/pgo
+		llvm-profdata merge -output=${CONFIG[PGO_DIR]}/default.profdata ${CONFIG[PGO_DIR]}
 	fi
 fi
 
@@ -1191,7 +1260,7 @@ if [[ $arch == x86_64* ]] || [[ $arch == aarch64* ]]; then
 	fi
 	# check gas version on aarch64
 	if [[ $arch == aarch64* ]]; then
-		ver=$(as --version 2> /dev/null | awk 'NR==1{print $7}')
+		ver=$(as --version 2> /dev/null | awk '/GNU assembler/{print $NF}')
 		if lt "$ver" 2.24; then
 			# ISA-L, compression & crypto require gas version 2.24 or newer.
 			CONFIG[ISAL]=n
@@ -1210,15 +1279,21 @@ fi
 # now either configure ISA-L or disable unavailable features
 if [[ "${CONFIG[ISAL]}" = "y" ]]; then
 	cd $rootdir/isa-l
-	ISAL_LOG=$rootdir/isa-l/spdk-isal.log
+	ISAL_LOG=$rootdir/.spdk-isal.log
 	if [[ -n "${CONFIG[CROSS_PREFIX]}" ]]; then
 		ISAL_OPTS=("--host=${CONFIG[CROSS_PREFIX]}")
 	else
 		ISAL_OPTS=()
 	fi
+	if [[ "${CONFIG[SHARED]}" = "y" ]]; then
+		ISAL_OPTS+=("--enable-shared=yes")
+	else
+		ISAL_OPTS+=("--enable-shared=no")
+	fi
+	ISAL_OPTS+=("--prefix=${CONFIG[PREFIX]}")
 	echo -n "Configuring ISA-L (logfile: $ISAL_LOG)..."
 	./autogen.sh &> $ISAL_LOG
-	./configure CFLAGS="-fPIC -g -O2" "${ISAL_OPTS[@]}" --enable-shared=no >> $ISAL_LOG 2>&1
+	./configure CFLAGS="-fPIC -g -O2 -fuse-ld=$LD_TYPE -Wno-unused-command-line-argument" "${ISAL_OPTS[@]}" --enable-shared=no >> $ISAL_LOG 2>&1
 	echo "done."
 	cd $rootdir
 else
@@ -1239,14 +1314,19 @@ if [[ "${CONFIG[ISAL]}" = "y" ]]; then
 	fi
 
 	cd $rootdir/isa-l-crypto
-	ISAL_CRYPTO_LOG=$rootdir/isa-l-crypto/spdk-isal-crypto.log
+	ISAL_CRYPTO_LOG=$rootdir/.spdk-isal-crypto.log
 	if [[ -n "${CONFIG[CROSS_PREFIX]}" ]]; then
 		ISAL_CRYPTO_OPTS+=("--host=${CONFIG[CROSS_PREFIX]}")
 	fi
-	ISAL_CRYPTO_OPTS+=("--enable-shared=no")
+	if [[ "${CONFIG[SHARED]}" = "y" ]]; then
+		ISAL_CRYPTO_OPTS+=("--enable-shared=yes")
+	else
+		ISAL_CRYPTO_OPTS+=("--enable-shared=no")
+	fi
+	ISAL_CRYPTO_OPTS+=("--prefix=${CONFIG[PREFIX]}")
 	echo -n "Configuring ISA-L-crypto (logfile: $ISAL_CRYPTO_LOG)..."
 	./autogen.sh &> $ISAL_CRYPTO_LOG
-	./configure CFLAGS="-fPIC -g -O2" "${ISAL_CRYPTO_OPTS[@]}" >> $ISAL_CRYPTO_LOG 2>&1
+	./configure CFLAGS="-fPIC -g -O2 -fuse-ld=$LD_TYPE -Wno-unused-command-line-argument" "${ISAL_CRYPTO_OPTS[@]}" >> $ISAL_CRYPTO_LOG 2>&1
 	echo "done."
 	cd $rootdir
 	CONFIG[ISAL_CRYPTO]=y
@@ -1269,6 +1349,62 @@ if [[ "${CONFIG[AVAHI]}" = "y" ]]; then
 		echo "--with-avahi requires libavahi-client and libavahi-common."
 		echo "Please install then re-run this script."
 		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[GOLANG]}" = "y" ]]; then
+	if ! go version 2> /dev/null; then
+		echo "--with-golang requires Go installation."
+		echo "Please install then re-run this script."
+		exit 1
+	fi
+fi
+
+if [[ -n ${CONFIG[MAX_LCORES]} ]]; then
+	if [[ ! ${CONFIG[MAX_LCORES]} =~ ^([1-9][0-9]*|detect)$ ]] || ((CONFIG[MAX_LCORES] > 1024)); then
+		echo "ERROR: Max number of lcores must be a decimal number in range [1..1024] or 'detect' (given: ${CONFIG[MAX_LCORES]})"
+		exit 1
+	fi
+fi
+
+if [[ -n ${CONFIG[MAX_NUMA_NODES]} ]]; then
+	if [[ ! ${CONFIG[MAX_NUMA_NODES]} =~ ^([1-9][0-9]*)$ ]] || ((CONFIG[MAX_NUMA_NODES] > 16)); then
+		echo "ERROR: Max number of lcores must be a decimal number in range [1..16] (given: ${CONFIG[MAX_LCORES]})"
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[FSDEV]}" = "n" ]]; then
+	if [[ "$AIO_FSDEV_REQUIRED" = "y" ]]; then
+		echo "ERROR: --with-aio-fsdev cannot be specified as fsdev is disabled."
+		exit 1
+	fi
+
+	# if AIO_FSDEV is not explicitly required by user, we just silently disable it
+	CONFIG[AIO_FSDEV]=n
+fi
+
+if [[ "${CONFIG[AIO_FSDEV]}" = "y" ]]; then
+	if echo -e '#define _GNU_SOURCE\n#include <unistd.h>\n' \
+		'int main(void) { return copy_file_range(0, 0, 0, 0, 0, 0); }\n' \
+		| "${BUILD_CMD[@]}" - 2> /dev/null; then
+		CONFIG[COPY_FILE_RANGE]=y
+	else
+		CONFIG[COPY_FILE_RANGE]=n
+	fi
+	if echo -e '#include <sys/stat.h>\n' \
+		'int main(void) { struct stat s; s.st_atime = s.st_atime; return 0 ;}\n' \
+		| "${BUILD_CMD[@]}" - 2> /dev/null; then
+		CONFIG[HAVE_STRUCT_STAT_ST_ATIM]=y
+		CONFIG[HAVE_STRUCT_STAT_ST_ATIMESPEC]=n
+	elif echo -e '#include <sys/stat.h>\n' \
+		'int main(void) { struct stat s; s.st_atimespec = s.st_atimespec; return 0; }\n' \
+		| "${BUILD_CMD[@]}" - 2> /dev/null; then
+		CONFIG[HAVE_STRUCT_STAT_ST_ATIM]=n
+		CONFIG[HAVE_STRUCT_STAT_ST_ATIMESPEC]=y
+	else
+		CONFIG[HAVE_STRUCT_STAT_ST_ATIM]=n
+		CONFIG[HAVE_STRUCT_STAT_ST_ATIMESPEC]=n
 	fi
 fi
 
diff --git a/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/lib/Makefile b/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/lib/Makefile
--- a/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/lib/Makefile
+++ b/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/lib/Makefile
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2012-2022, Intel Corporation
+# Copyright (c) 2012-2023, Intel Corporation
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -50,58 +50,80 @@ USE_YASM ?= n
 YASM ?= yasm
 NASM ?= nasm
 
+CC ?= gcc
+
+OBJ_DIR ?= obj
+LIB_DIR ?= .
+
+# skip version detection with clean or style target
+ifneq ($(MAKECMDGOALS),clean)
+ifneq ($(MAKECMDGOALS),style)
+
+# MINGW should be non-zero value if detected
+MINGW ?= $(shell $(CC) -dM -E - < /dev/null | grep -i mingw | wc -l | sed 's/^ *//')
+
+ifeq ($(MINGW),0)
+MULT = \*
+else
+MULT = \\*
+endif
+
 # Detect NASM version (minimum version required: 2.14)
 NASM_VERSION = $(shell $(NASM) -v | cut -d " " -f 3)
 
 NASM_MAJOR_REQ = 2
 NASM_MINOR_REQ = 14
+NASM_MIN_REQ = $(shell expr $(NASM_MAJOR_REQ) $(MULT) 100 + $(NASM_MINOR_REQ) )
 
 ifeq ($(NASM_VERSION),)
 $(error "NASM is not installed! Minimum required version: $(NASM_MAJOR_REQ).$(NASM_MINOR_REQ)")
 else
 NASM_MAJOR_VER = $(shell echo $(NASM_VERSION) | cut -d "." -f 1)
 NASM_MINOR_VER = $(shell echo $(NASM_VERSION) | cut -d "." -f 2 | cut -c 1-2)
-NASM_GE_MAJOR = $(shell [ $(NASM_MAJOR_VER) -ge $(NASM_MAJOR_REQ) ] && echo true)
-NASM_GE_MINOR = $(shell [ $(NASM_MINOR_VER) -ge $(NASM_MINOR_REQ) ] && echo true)
-ifneq ($(NASM_GE_MAJOR),true)
-$(warning "NASM version found: $(NASM_VERSION)")
-$(error "Minimum required: $(NASM_MAJOR_REQ).$(NASM_MINOR_REQ)")
-endif
-ifneq ($(NASM_GE_MINOR),true)
-$(warning "NASM version found: $(NASM_VERSION)")
-$(error "Minimum required: $(NASM_MAJOR_REQ).$(NASM_MINOR_REQ)")
-endif
-endif
+NASM_VER = $(shell expr $(NASM_MAJOR_VER) $(MULT) 100 + $(NASM_MINOR_VER) )
 
-OBJ_DIR ?= obj
-LIB_DIR ?= .
+NASM_GE_REQ = $(shell [ $(NASM_VER) -ge $(NASM_MIN_REQ) ] && echo true)
+
+$(info NASM '$(NASM)' version: $(NASM_VERSION))
+
+ifneq ($(NASM_GE_REQ),true)
+$(error "Minimum required NASM version: $(NASM_MAJOR_REQ).$(NASM_MINOR_REQ)")
+endif # NASM_GE_REQ
+endif # NASM_VERSION
+
+# Minimum version of NASM with AVX_IFMA support: 2.16
+AVX_IFMA := y
+NASM_MAJOR_AVX_IFMA = 2
+NASM_MINOR_AVX_IFMA = 16
+NASM_MIN_IFMA_REQ = $(shell expr $(NASM_MAJOR_AVX_IFMA) $(MULT) 100 + $(NASM_MINOR_AVX_IFMA) )
+
+NASM_IFMA_GE_REQ = $(shell [ $(NASM_VER) -ge $(NASM_MIN_IFMA_REQ) ] && echo true)
+ifneq ($(NASM_IFMA_GE_REQ),true)
+$(warning Minimum required NASM version for AVX-IFMA: $(NASM_MAJOR_AVX_IFMA).$(NASM_MINOR_AVX_IFMA). AVX-IFMA code not compiled - update NASM.)
+AVX_IFMA := n
+endif # NASM_AVX_IFMA_GET_REQ
 
 INCLUDE_DIRS := include . no-aesni
 INCLUDES := $(foreach i,$(INCLUDE_DIRS),-I $i)
-
-CC ?= gcc
-# MINGW should be non-zero value if detected
-MINGW ?= $(shell $(CC) -dM -E - < /dev/null | grep -i mingw | wc -l | sed 's/^ *//')
 
 # if "-z ibt" is supported then assume "-z shstk, -z cet-report=error" are also supported
 # "-fcf-protection" needs to be checked separately
 ifeq ($(MINGW),0)
 CC_HAS_CET = $(and $(shell $(CC) --target-help 2> /dev/null | grep -m1 -e "-z ibt" | wc -l), \
 	$(shell $(CC) --help=common 2> /dev/null | grep -m1 -e "-fcf-protection" | wc -l))
-CET_LDFLAGS=-r -z ibt -z shstk
 endif
-CFLAGS := -DNO_COMPAT_IMB_API_053 $(EXTRA_CFLAGS) $(INCLUDES) \
+CFLAGS := $(EXTRA_CFLAGS) $(INCLUDES) \
 	-W -Wall -Wextra -Wmissing-declarations -Wpointer-arith \
 	-Wcast-qual -Wundef -Wwrite-strings  \
 	-Wformat -Wformat-security \
 	-Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels \
 	-Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition \
-	-fno-delete-null-pointer-checks -fwrapv
+	-fno-delete-null-pointer-checks -fwrapv -std=c99
 
-# SPDK crypto needs shared but -fPIC so to make it clear what
-# we are doing, we just comment out the CFLAGS below and
-# explicitly set them in our relevant makefile.
+# Let SPDK decide when to pass -fPIC,
+# rather than forcing it here.
 #CFLAGS += -fPIC
+
 # -fno-strict-overflow is not supported by clang
 ifneq ($(CC),clang)
 CFLAGS += -fno-strict-overflow
@@ -113,6 +135,10 @@ endif
 
 ifeq ($(CC_HAS_CET),1)
 CFLAGS += -fcf-protection=full
+endif
+
+ifeq ($(AVX_IFMA), y)
+CFLAGS += -DAVX_IFMA
 endif
 
 ASM_INCLUDE_DIRS := .
@@ -188,6 +214,7 @@ OPT_NOAESNI := -msse4.2 -mno-aes -mno-pclmul
 ifeq ($(CC),$(filter $(CC),gcc cc))
 GCC_VERSION = $(shell $(CC) -dumpversion | cut -d. -f1)
 GCC_GE_V5 = $(shell [ $(GCC_VERSION) -ge 5 ] && echo true)
+$(info CC '$(CC)' version: $(GCC_VERSION))
 ifeq ($(GCC_GE_V5),true)
 OPT_SSE := -march=nehalem -maes -mpclmul
 OPT_AVX := -march=sandybridge -maes -mpclmul
@@ -201,6 +228,7 @@ endif
 ifeq ($(CC),$(filter $(CC),clang))
 CLANG_VERSION = $(shell $(CC) --version | head -n 1 | cut -d ' ' -f 3)
 CLANG_GE_V381 = $(shell test "$(CLANG_VERSION)" \> "3.8.0" && echo true)
+$(info CLANG '$(CC)' version: $(CLANG_VERSION))
 ifeq ($(CLANG_GE_V381),true)
 OPT_SSE := -march=nehalem -maes -mpclmul
 OPT_AVX := -march=sandybridge -maes -mpclmul
@@ -222,16 +250,16 @@ LDFLAGS += -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now
 endif
 LIBPERM = 0755
 ifeq ($(CC_HAS_CET),1)
-LDFLAGS += -fcf-protection=full -Wl,-z,ibt -Wl,-z,shstk -Wl,-z,cet-report=error
+LDFLAGS += -Wl,-z,ibt -Wl,-z,shstk -Wl,-z,cet-report=error
 endif
 else
 LIBNAME = $(LIB).a
 LIBPERM = 0644
 LDFLAGS += -g
-ifeq ($(CC_HAS_CET),1)
-LDFLAGS += -fcf-protection=full
 endif
-endif
+
+endif # style target
+endif # clean target
 
 # warning messages
 SAFE_PARAM_MSG1="SAFE_PARAM option not set."
@@ -267,9 +295,12 @@ c_lib_objs := \
 	aes_xcbc_expand_key.o \
 	md5_one_block.o \
 	sha_sse.o \
+	sha_ni_sse.o \
 	sha_mb_sse.o \
 	sha_ni_mb_sse.o \
 	sha_avx.o \
+	sha_avx2.o \
+	sha_avx512.o \
 	sha_mb_avx.o \
 	sha_mb_avx2.o \
 	sha_mb_avx512.o \
@@ -294,7 +325,13 @@ c_lib_objs := \
 	mb_mgr_auto.o \
 	error.o \
 	ooo_mgr_reset.o \
-	self_test.o
+	self_test.o \
+	quic_aes_gcm.o \
+	quic_hp_aes_ecb.o \
+	quic_hp_chacha20.o \
+	quic_chacha20_poly1305.o \
+	hmac_ipad_opad.o \
+	cipher_suite_id.o
 
 ifeq ($(AESNI_EMU), y)
 c_lib_objs := $(c_lib_objs) \
@@ -304,6 +341,10 @@ c_lib_objs := $(c_lib_objs) \
 	snow3g_sse_no_aesni.o
 endif
 
+ifeq ($(AVX_IFMA), y)
+c_lib_objs := $(c_lib_objs) \
+	mb_mgr_avx2_t3.o
+endif
 #
 # List of ASM modules (root directory/common)
 #
@@ -322,7 +363,10 @@ asm_generic_lib_objs := \
 	crc32_refl_const.o \
 	crc32_const.o \
 	poly1305.o \
-	chacha20_poly1305.o
+	chacha20_poly1305.o \
+	mbcpuid.o \
+	atomic.o \
+	sm3.o
 
 #
 # List of ASM modules (no-aesni directory)
@@ -373,7 +417,8 @@ asm_noaesni_lib_objs := \
 	crc32_iuup_sse_no_aesni.o \
 	crc32_wimax_sse_no_aesni.o \
 	snow_v_sse_no_aesni.o \
-	snow3g_uia2_sse_no_aesni.o
+	snow3g_uia2_sse_no_aesni.o \
+	sm4_sse_no_aesni.o
 
 #
 # List of ASM modules (sse directory)
@@ -395,6 +440,7 @@ asm_sse_lib_objs := \
 	aes128_cntr_by8_sse.o \
 	aes192_cntr_by8_sse.o \
 	aes256_cntr_by8_sse.o \
+	aes_ecb_quic_x8_sse.o \
 	aes128_ecb_by4_sse.o \
 	aes192_ecb_by4_sse.o \
 	aes256_ecb_by4_sse.o \
@@ -416,6 +462,8 @@ asm_sse_lib_objs := \
 	sha256_one_block_sse.o \
 	sha384_one_block_sse.o \
 	sha512_one_block_sse.o \
+	sha1_ni_one_block_sse.o \
+	sha256_ni_one_block_sse.o \
 	sha512_x2_sse.o \
 	sha256_mult_sse.o \
 	sha1_ni_x2_sse.o \
@@ -484,7 +532,8 @@ asm_sse_lib_objs := \
 	chacha20_sse.o \
 	memcpy_sse.o \
 	snow_v_sse.o \
-	snow3g_uia2_by4_sse.o
+	snow3g_uia2_by4_sse.o \
+	sm4_sse.o
 
 #
 # List of ASM modules (avx directory)
@@ -505,6 +554,7 @@ asm_avx_lib_objs := \
 	aes128_ecb_by8_avx.o \
 	aes192_ecb_by8_avx.o \
 	aes256_ecb_by8_avx.o \
+	aes_ecb_quic_x8_avx.o \
 	aes_cfb_avx.o \
 	aes128_cbc_mac_x8_avx.o \
 	aes256_cbc_mac_x8_avx.o \
@@ -571,9 +621,13 @@ asm_avx2_lib_objs := \
 	sha256_oct_avx2.o \
 	sha512_x4_avx2.o \
 	zuc_x8_avx2.o \
+	zuc_x8_gfni_avx2.o \
 	aes128_ecb_vaes_avx2.o \
 	aes192_ecb_vaes_avx2.o \
 	aes256_ecb_vaes_avx2.o \
+	aes128_cntr_vaes_avx2.o \
+	aes192_cntr_vaes_avx2.o \
+	aes256_cntr_vaes_avx2.o \
 	mb_mgr_hmac_md5_flush_avx2.o \
 	mb_mgr_hmac_md5_submit_avx2.o \
 	mb_mgr_hmac_sha1_flush_avx2.o \
@@ -587,7 +641,14 @@ asm_avx2_lib_objs := \
 	mb_mgr_hmac_sha512_flush_avx2.o \
 	mb_mgr_hmac_sha512_submit_avx2.o \
 	mb_mgr_zuc_submit_flush_avx2.o \
+	mb_mgr_zuc_submit_flush_gfni_avx2.o \
 	chacha20_avx2.o
+
+#
+# List of ASM modules (avx2_t3 directory)
+#
+asm_avx2_ifma_lib_objs := \
+	poly_fma_avx2.o
 
 #
 # List of ASM modules (avx512 directory)
@@ -598,6 +659,7 @@ asm_avx512_lib_objs := \
 	sha512_x8_avx512.o \
 	des_x16_avx512.o \
 	aes_ecb_vaes_avx512.o \
+	aes_ecb_quic_vaes_avx512.o \
 	aes_cntr_api_by16_vaes_avx512.o \
 	aes_cntr_bit_api_by16_vaes_avx512.o \
 	aes_cntr_ccm_api_by16_vaes_avx512.o \
@@ -671,16 +733,16 @@ asm_sse_gcm_objs := \
 	gcm128_sgl_api_by8_sse.o gcm192_sgl_api_by8_sse.o gcm256_sgl_api_by8_sse.o \
 	gcm128_gmac_api_by8_sse.o gcm192_gmac_api_by8_sse.o gcm256_gmac_api_by8_sse.o
 
-asm_avx_gcm_objs := \
-	aes128_gcm_by8_avx.o aes192_gcm_by8_avx.o aes256_gcm_by8_avx.o
+asm_avx_gcm_objs :=
 
 asm_avx2_gcm_objs := \
-	aes128_gcm_by8_avx2.o aes192_gcm_by8_avx2.o aes256_gcm_by8_avx2.o
+	aes128_gcm_by8_avx2.o aes192_gcm_by8_avx2.o aes256_gcm_by8_avx2.o \
+	aes128_gcm_vaes_avx2.o aes192_gcm_vaes_avx2.o aes256_gcm_vaes_avx2.o
 
 asm_avx512_gcm_objs := \
-	aes128_gcm_by48_api_vaes_avx512.o aes192_gcm_by48_api_vaes_avx512.o aes256_gcm_by48_api_vaes_avx512.o \
-	aes128_gcm_by48_sgl_api_vaes_avx512.o aes192_gcm_by48_sgl_api_vaes_avx512.o aes256_gcm_by48_sgl_api_vaes_avx512.o \
-	aes128_gmac_by48_api_vaes_avx512.o aes192_gmac_by48_api_vaes_avx512.o aes256_gmac_by48_api_vaes_avx512.o \
+	aes128_gcm_api_vaes_avx512.o aes192_gcm_api_vaes_avx512.o aes256_gcm_api_vaes_avx512.o \
+	aes128_gcm_sgl_api_vaes_avx512.o aes192_gcm_sgl_api_vaes_avx512.o aes256_gcm_sgl_api_vaes_avx512.o \
+	aes128_gmac_api_vaes_avx512.o aes192_gmac_api_vaes_avx512.o aes256_gmac_api_vaes_avx512.o \
 	aes128_gcm_by8_avx512.o aes192_gcm_by8_avx512.o aes256_gcm_by8_avx512.o
 
 #
@@ -695,6 +757,10 @@ asm_obj_files := $(asm_generic_lib_objs) \
 ifeq ($(AESNI_EMU), y)
 asm_obj_files := $(asm_obj_files) $(asm_noaesni_lib_objs) $(asm_noaesni_gcm_objs)
 endif
+ifeq ($(AVX_IFMA), y)
+asm_obj_files := $(asm_obj_files) $(asm_avx2_ifma_lib_objs)
+endif
+
 c_obj_files := $(c_lib_objs) $(c_gcm_objs)
 
 #
@@ -721,9 +787,22 @@ dep_target_files := $(dep_files:%=$(OBJ_DIR)/%)
 
 all: $(LIB_DIR)/$(LIBNAME)
 
+STR_FILTER = ""
+ifneq ($(AESNI_EMU),y)
+ifneq ($(AVX_IFMA),y)
+STR_FILTER = "_no_aesni\|_avx2_t3"
+else
+STR_FILTER = "_no_aesni"
+endif
+else
+ifneq ($(AVX_IFMA),y)
+STR_FILTER = "_avx2_t3"
+endif
+endif
+
 $(LIB)_lnk.def: $(LIB).def
-ifneq ($(AESNI_EMU), y)
-	grep -v _no_aesni $(LIB).def > $(LIB)_lnk.def
+ifneq ($(STR_FILTER), "")
+	grep -v $(STR_FILTER) $(LIB).def > $(LIB)_lnk.def
 else
 	cp -f $(LIB).def $(LIB)_lnk.def
 endif
@@ -807,10 +886,6 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
 
 $(OBJ_DIR)/%.o:sse_t1/%.c
 	$(CC) -MMD $(OPT_SSE) -c $(CFLAGS) $< -o $@
@@ -820,10 +895,6 @@ ifeq ($(USE_YASM),y)
 	$(YASM) $(YASM_FLAGS) $< -o $@
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
-endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
 endif
 
 $(OBJ_DIR)/%.o:sse_t2/%.c
@@ -835,10 +906,6 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
 
 $(OBJ_DIR)/%.o:sse_t3/%.c
 	$(CC) -MMD $(OPT_SSE) -c $(CFLAGS) $< -o $@
@@ -848,10 +915,6 @@ ifeq ($(USE_YASM),y)
 	$(YASM) $(YASM_FLAGS) $< -o $@
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
-endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
 endif
 
 $(OBJ_DIR)/%.o:avx_t1/%.c
@@ -863,10 +926,6 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
 
 $(OBJ_DIR)/%.o:avx_t2/%.c
 	$(CC) -MMD $(OPT_AVX) -c $(CFLAGS) $< -o $@
@@ -877,11 +936,6 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
-
 $(OBJ_DIR)/%.o:avx2_t1/%.c
 	$(CC) -MMD $(OPT_AVX2) -c $(CFLAGS) $< -o $@
 
@@ -891,11 +945,6 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
-
 $(OBJ_DIR)/%.o:avx2_t2/%.c
 	$(CC) -MMD $(OPT_AVX2) -c $(CFLAGS) $< -o $@
 
@@ -905,9 +954,14 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
+$(OBJ_DIR)/%.o:avx2_t3/%.c
+	$(CC) -MMD $(OPT_AVX2) -c $(CFLAGS) $< -o $@
+
+$(OBJ_DIR)/%.o:avx2_t3/%.asm
+ifeq ($(USE_YASM),y)
+	$(YASM) $(YASM_FLAGS) $< -o $@
+else
+	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
 
 $(OBJ_DIR)/%.o:avx512_t1/%.c
@@ -919,10 +973,6 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
 
 $(OBJ_DIR)/%.o:avx512_t2/%.c
 	$(CC) -MMD $(OPT_AVX512) -c $(CFLAGS) $< -o $@
@@ -933,10 +983,6 @@ ifeq ($(USE_YASM),y)
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
 endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
 
 $(OBJ_DIR)/%.o:no-aesni/%.c
 	$(CC) -MMD $(OPT_NOAESNI) -c $(CFLAGS_NO_SIMD) $< -o $@
@@ -946,10 +992,6 @@ ifeq ($(USE_YASM),y)
 	$(YASM) $(YASM_FLAGS) $< -o $@
 else
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
-endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
 endif
 
 $(OBJ_DIR):
@@ -966,10 +1008,9 @@ TAGS:
 
 .PHONY: clean
 clean:
-	rm -Rf $(target_obj_files)
-	rm -Rf $(dep_target_files)
-	rm -f $(LIB_DIR)/$(LIB)_lnk.def
-	rm -f $(LIB_DIR)/$(LIB).a $(LIB_DIR)/$(LIB).so* $(LIB_DIR)/$(LIB).dll
+	-rm -Rf $(OBJ_DIR)
+	-rm -f $(LIB_DIR)/$(LIB)_lnk.def
+	-rm -f $(LIB_DIR)/$(LIB).a $(LIB_DIR)/$(LIB).so* $(LIB_DIR)/$(LIB).dll
 
 .PHONY: doxy
 doxy:
@@ -1009,6 +1050,8 @@ help:
 	@echo "SAFE_OPTIONS=n"
 	@echo "          - Disable all safe options (enabled by default)"
 
+.PHONY: style
+style: clang-format checkpatch
 
 CHECKPATCH ?= checkpatch.pl
 # checkpatch ignore settings:
@@ -1022,13 +1065,7 @@ CHECKPATCH ?= checkpatch.pl
 #
 # NOTE: these flags cannot be broken into multiple lines due to
 #       spaces injected by make
-CHECKPATCH_FLAGS = --no-tree --no-signoff --emacs --no-color --ignore CODE_INDENT,INITIALISED_STATIC,LEADING_SPACE,SPLIT_STRING,UNSPECIFIED_INT,ARRAY_SIZE,BLOCK_COMMENT_STYLE,GLOBAL_INITIALISERS,NEW_TYPEDEFS,AVOID_EXTERNS,COMPLEX_MACRO,PREFER_ALIGNED,USE_FUNC,CONSTANT_COMPARISON,SPACING,GCC_BINARY_CONSTANT
-
-%.c_style_check : %.c
-	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
-
-%.h_style_check : %.h
-	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
+CHECKPATCH_FLAGS = --no-tree --no-signoff --emacs --no-color --max-line-length=100 --ignore CODE_INDENT,INITIALISED_STATIC,LEADING_SPACE,SPLIT_STRING,UNSPECIFIED_INT,ARRAY_SIZE,BLOCK_COMMENT_STYLE,GLOBAL_INITIALISERS,NEW_TYPEDEFS,AVOID_EXTERNS,COMPLEX_MACRO,PREFER_ALIGNED,USE_FUNC,CONSTANT_COMPARISON,SPACING,GCC_BINARY_CONSTANT,VOLATILE
 
 %.asm_style_check : %.asm
 	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
@@ -1036,12 +1073,37 @@ CHECKPATCH_FLAGS = --no-tree --no-signoff --emacs --no-color --ignore CODE_INDEN
 %.inc_style_check : %.inc
 	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
 
-SOURCES_DIRS := . sse avx avx2 avx512 include no-aesni
-SOURCES := $(foreach dir,$(SOURCES_DIRS),$(wildcard $(dir)/*.[ch]) $(wildcard $(dir)/*.asm) $(wildcard $(dir)/*.inc))
-SOURCES_STYLE := $(foreach infile,$(SOURCES),$(infile)_style_check)
+SOURCES_DIRS := . sse_t1 sse_t2 sse_t3 avx_t1 avx_t2 avx2_t1 avx_t2 avx2_t3 avx512_t1 avx512_t2 x86_64 include no-aesni
+ASM_SOURCES := $(foreach dir,$(SOURCES_DIRS), $(wildcard $(dir)/**/*.asm) $(wildcard $(dir)/**/*.inc))
 
-.PHONY: style
-style: $(SOURCES_STYLE)
+.PHONY: checkpatch
+checkpatch:
+	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $(ASM_SOURCES)
+
+.PHONY: clang-format
+CLANGFORMAT?=clang-format
+clang-format:
+	@for file in $(wildcard ./*.[ch]) $(wildcard ./**/*.[ch]); do \
+		echo "Checking style $$file"; \
+		$(CLANGFORMAT) -style=file "$$file" | diff "$$file" - | tee /dev/stderr | [ $$(wc -c) -eq 0 ] || \
+		{ echo "ERROR: $$file has style problems"; exit 1; } \
+	done
+
+# cppcheck analysis check
+CPPCHECK ?= cppcheck
+CPPCHECK_OPTS ?= -I./include -I./
+CPPCHECK_FLAGS = -j $(shell getconf _NPROCESSORS_ONLN)
+CPPCHECK_FLAGS1 = --cppcheck-build-dir=.cppcheck $(CPPCHECK_FLAGS)
+CPPCHECK_FLAGS2 = --cppcheck-build-dir=.bughunt $(CPPCHECK_FLAGS)
+.PHONY: cppcheck
+cppcheck:
+	mkdir -p .cppcheck
+	$(CPPCHECK) --force --enable=all $(CPPCHECK_FLAGS1) $(CPPCHECK_OPTS) ./
+
+.PHONY: bughunt
+bughunt:
+	mkdir -p .bughunt
+	$(CPPCHECK) --bug-hunting --inconclusive $(CPPCHECK_FLAGS2) $(CPPCHECK_OPTS) ./
 
 # if target not clean or rinse then make dependencies
 ifneq ($(MAKECMDGOALS),clean)
diff --git a/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/perf/Makefile b/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/perf/Makefile
--- a/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/perf/Makefile
+++ b/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/perf/Makefile
@@ -1,4 +1,4 @@
-# Copyright (c) 2017-2022, Intel Corporation
+# Copyright (c) 2017-2023, Intel Corporation
 # 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -23,20 +23,20 @@
 # OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-EXE=ipsec_perf
+EXE=imb-perf
 INSTPATH ?= /usr/include/intel-ipsec-mb.h
 LIB_DIR ?= ../lib
 NASM ?= nasm
 
 MINGW ?= $(shell $(CC) -dM -E - < /dev/null | grep -i mingw | wc -l | sed 's/^ *//')
 
-CFLAGS = -D_GNU_SOURCE -DNO_COMPAT_IMB_API_053 $(INCLUDES) \
+CFLAGS = -D_GNU_SOURCE $(INCLUDES) \
 	-W -Wall -Wextra -Wmissing-declarations -Wpointer-arith \
 	-Wcast-qual -Wundef -Wwrite-strings  \
 	-Wformat -Wformat-security \
 	-Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels \
 	-Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition \
-	-pthread -fno-delete-null-pointer-checks -fwrapv
+	-pthread -fno-delete-null-pointer-checks -fwrapv -std=c99
 
 # -fno-strict-overflow is not supported by clang
 ifneq ($(CC),clang)
@@ -55,7 +55,6 @@ endif
 ifeq ($(MINGW),0)
 CC_HAS_CET = $(and $(shell $(CC) --target-help 2> /dev/null | grep -m1 -e "-z ibt" | wc -l), \
 	$(shell $(CC) --help=common 2> /dev/null | grep -m1 -e "-fcf-protection" | wc -l))
-CET_LDFLAGS=-r -z ibt -z shstk
 endif
 ifeq ($(CC_HAS_CET),1)
 CFLAGS += -fcf-protection=full
@@ -65,7 +64,7 @@ ifeq ($(MINGW),0)
 LDFLAGS = -fPIE -z noexecstack -z relro -z now -pthread
 endif
 ifeq ($(CC_HAS_CET),1)
-LDFLAGS += -fcf-protection=full -Wl,-z,ibt -Wl,-z,shstk -Wl,-z,cet-report=error
+LDFLAGS += -Wl,-z,ibt -Wl,-z,shstk -Wl,-z,cet-report=error
 endif
 LDLIBS = -lIPSec_MB
 
@@ -74,7 +73,7 @@ ifeq ("$(shell test -e $(INSTPATH) && echo -n yes)","yes")
 CFLAGS +=
 else
 # library not installed
-CFLAGS +=  -I../lib/include -I../lib
+CFLAGS += -I../lib
 LDFLAGS += -L$(LIB_DIR)
 endif
 
@@ -93,8 +92,8 @@ endif
 SOURCES := ipsec_perf.c msr.c
 ASM_SOURCES := misc.asm
 OBJECTS := $(SOURCES:%.c=%.o) $(ASM_SOURCES:%.asm=%.o)
+DEPFILES := $(OBJECTS:%.o=%.d)
 
-CHECKPATCH ?= checkpatch.pl
 CPPCHECK ?= cppcheck
 
 .PHONY: all clean style cppcheck
@@ -102,29 +101,53 @@ CPPCHECK ?= cppcheck
 # rule for compiling assembly code with producing dependencies
 %.o:%.asm
 	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
 
 all: $(EXE)
 
 $(EXE): $(OBJECTS)
 	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
 
-ipsec_perf.o: $(SOURCES)
-
 .PHONY: clean
 clean:
 	-rm -f $(OBJECTS)
+	-rm -f $(DEPFILES)
 	-rm -f $(EXE)
 
-SOURCES_STYLE := $(foreach infile,$(SOURCES),-f $(infile))
-CHECKPATCH?=checkpatch.pl
 .PHONY: style
-style:
+style: clang-format checkpatch
+
+.PHONY: clang-format
+CLANGFORMAT?=clang-format
+clang-format:
+	@for file in $(wildcard ./*.[ch]) $(wildcard ./**/*.[ch]); do \
+		echo "Checking style $$file"; \
+		$(CLANGFORMAT) -style=file "$$file" | diff "$$file" - | tee /dev/stderr | [ $$(wc -c) -eq 0 ] || \
+		{ echo "ERROR: $$file has style problems"; exit 1; } \
+	done
+
+.PHONY: checkpatch
+SOURCES_STYLE := $(foreach infile,$(ASM_SOURCES),-f $(infile))
+CHECKPATCH?=checkpatch.pl
+checkpatch:
 	$(CHECKPATCH) --no-tree --no-signoff --emacs --no-color \
 --ignore CODE_INDENT,INITIALISED_STATIC,LEADING_SPACE,SPLIT_STRING,\
 UNSPECIFIED_INT,ARRAY_SIZE,BLOCK_COMMENT_STYLE,GLOBAL_INITIALISERS,\
 COMPLEX_MACRO,SPACING,STORAGE_CLASS,USE_FUNC,NEW_TYPEDEFS,VOLATILE,\
-CONSTANT_COMPARISON $(SOURCES_STYLE)
+CONSTANT_COMPARISON --max-line-length=100 $(SOURCES_STYLE)
+
+# cppcheck analysis check
+CPPCHECK ?= cppcheck
+CPPCHECK_OPTS ?= -I../lib -I./
+CPPCHECK_FLAGS ?= -j $(shell getconf _NPROCESSORS_ONLN)
+CPPCHECK_FLAGS1 ?= --cppcheck-build-dir=.cppcheck $(CPPCHECK_FLAGS)
+CPPCHECK_FLAGS2 ?= --cppcheck-build-dir=.bughunt $(CPPCHECK_FLAGS)
+
+.PHONY: cppcheck
+cppcheck:
+	mkdir -p .cppcheck
+	$(CPPCHECK) --force --enable=all $(CPPCHECK_FLAGS1) $(CPPCHECK_OPTS) ./
+
+.PHONY: bughunt
+bughunt:
+	mkdir -p .bughunt
+	$(CPPCHECK) --bug-hunting --inconclusive $(CPPCHECK_FLAGS2) $(CPPCHECK_OPTS) ./
diff --git a/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/test/Makefile b/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/test/Makefile
--- a/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/test/Makefile
+++ b/ceph/src/nvmeof/gateway/spdk/intel-ipsec-mb/test/Makefile
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2012-2022, Intel Corporation
+# Copyright (c) 2012-2023, Intel Corporation
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -25,189 +25,77 @@
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 
-TEST_APP := ipsec_MB_testapp
-XVALID_APP := ipsec_xvalid_test
-FUZZ_APP := job_api_fuzz_test
-ACVP_APP := acvp_app
-INSTPATH ?= /usr/include/intel-ipsec-mb.h
-LIB_DIR ?= ../lib
-
-USE_YASM ?= n
-YASM ?= yasm
-NASM ?= nasm
-
-MINGW ?= $(shell $(CC) -dM -E - < /dev/null | grep -i mingw | wc -l | sed 's/^ *//')
-
-CFLAGS = -MMD -D_GNU_SOURCE -DNO_COMPAT_IMB_API_053 \
-	-W -Wall -Wextra -Wmissing-declarations -Wpointer-arith \
-	-Wcast-qual -Wundef -Wwrite-strings  \
-	-Wformat -Wformat-security \
-	-Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels \
-	-Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition \
-	-fno-delete-null-pointer-checks -fwrapv
-
-# -fno-strict-overflow is not supported by clang
-ifneq ($(CC),clang)
-CFLAGS += -fno-strict-overflow
-endif
-
-# if "-z ibt" is supported then assume "-z shstk, -z cet-report=error" are also supported
-# "-fcf-protection" needs to be checked separately
-ifeq ($(MINGW),0)
-CC_HAS_CET = $(and $(shell $(CC) --target-help 2> /dev/null | grep -m1 -e "-z ibt" | wc -l), \
-	$(shell $(CC) --help=common 2> /dev/null | grep -m1 -e "-fcf-protection" | wc -l))
-CET_LDFLAGS=-r -z ibt -z shstk
-endif
-
-ifeq ($(CC_HAS_CET),1)
-CFLAGS += -fcf-protection=full
-endif
-
-YASM_FLAGS := -f x64 -f elf64 -X gnu -g dwarf2 -DLINUX -D__linux__
-ifeq ($(MINGW),0)
-CFLAGS += -DLINUX
-NASM_FLAGS := -Werror -felf64 -Xgnu -gdwarf -DLINUX -D__linux__
-else
-NASM_FLAGS := -Werror -fwin64 -Xvc -gcv8 -DWIN_ABI
-endif
-
-ifeq ($(MINGW),0)
-LDFLAGS = -fPIE -z noexecstack -z relro -z now
-else
-LDFLAGS = -fPIE
-endif
-
-ifeq ($(CC_HAS_CET),1)
-LDFLAGS += -fcf-protection=full -Wl,-z,ibt -Wl,-z,shstk -Wl,-z,cet-report=error
-endif
-LDLIBS = -lIPSec_MB
-
-ifeq ("$(shell test -r $(INSTPATH) && echo -n yes)","yes")
-# library installed
-CFLAGS +=
-else
-# library not installed
-CFLAGS +=  -I../lib/include -I../lib
-LDFLAGS += -L$(LIB_DIR)
-endif
-
-FUZZ_CFLAGS = -I../lib -L../lib $(CFLAGS) -g -fsanitize=fuzzer,address,leak
-
-DEBUG_OPT ?= -O0
-ifeq ($(DEBUG),y)
-CFLAGS += $(DEBUG_OPT) -DDEBUG -g
-LDFLAGS += -g
-else
-ifeq ($(MINGW),0)
-CFLAGS += -O3
-else
-CFLAGS += -O2
-endif
-endif
-
-ACVP_LOC ?= /usr/local/acvp
-ACVP_HDR ?= $(ACVP_LOC)/include
-ACVP_LIB ?= $(ACVP_LOC)/lib
-ACVP_CFLAGS = -I$(ACVP_HDR) $(CFLAGS)
-ACVP_LDFLAGS = -L$(ACVP_LIB) $(LDFLAGS)
-ACVP_LDLIBS = -lacvp $(LDLIBS)
-
-# ipsec_MB_testapp modules
-SOURCES := main.c gcm_test.c ctr_test.c customop_test.c des_test.c ccm_test.c \
-	cmac_test.c utils.c hmac_sha1_test.c hmac_sha256_sha512_test.c \
-	hmac_md5_test.c aes_test.c sha_test.c chained_test.c api_test.c pon_test.c \
-	ecb_test.c zuc_test.c kasumi_test.c snow3g_test.c direct_api_test.c clear_mem_test.c \
-	hec_test.c xcbc_test.c aes_cbcs_test.c crc_test.c chacha_test.c poly1305_test.c \
-	chacha20_poly1305_test.c null_test.c snow_v_test.c direct_api_param_test.c
-OBJECTS := $(SOURCES:%.c=%.o)
-
-ifneq ($(PIN_CEC_ROOT),)
-CFLAGS += -I$(PIN_CEC_ROOT)/include -DPIN_BASED_CEC
-endif
-
-# ipsec_xvalid_test modules
-XVALID_ASM := misc.asm
-XVALID_SOURCES := ipsec_xvalid.c utils.c
-XVALID_OBJECTS := $(XVALID_SOURCES:%.c=%.o) $(XVALID_ASM:%.asm=%.o)
-
-# fuzz modules
-FUZZ_SOURCES := job_api_fuzz_test.c
-
-# acvp_app modules
-ACVP_SOURCES := acvp_app_main.c utils.c
-
-# list of present dependency files
-DEP_FILES = $(wildcard ./*.d)
-
-# rule for compiling assembly code with producing dependencies
-%.o:%.asm
-ifeq ($(USE_YASM),y)
-	$(YASM) $(YASM_FLAGS) $< -o $@
-else
-	$(NASM) -MD $(@:.o=.d) -MT $@ -o $@ $(NASM_FLAGS) $<
-endif
-ifeq ($(CC_HAS_CET),1)
-	$(LD) $(CET_LDFLAGS) -o $@.tmp $@
-	mv $@.tmp $@
-endif
+KAT_APP := kat-app
+XVALID_APP := xvalid-app
+FUZZ_APP := fuzz-app
+ACVP_APP := acvp-app
+WYCHEPROOF_APP := wycheproof-app
 
 # targets come here
-all: $(TEST_APP) $(XVALID_APP) $(FUZZ_APP) $(ACVP_APP)
+all: $(KAT_APP) $(XVALID_APP) $(FUZZ_APP) $(ACVP_APP) $(WYCHEPROOF_APP)
 
-$(TEST_APP): $(OBJECTS)
-	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
+.PHONY: $(KAT_APP) $(XVALID_APP) $(FUZZ_APP) $(ACVP_APP) $(WYCHEPROOF_APP)
 
-$(XVALID_APP): $(XVALID_OBJECTS)
-	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
+$(KAT_APP):
+	$(MAKE) -C kat-app
 
-$(ACVP_APP): $(ACVP_SOURCES)
-ifneq ("$(wildcard $(ACVP_HDR))","")
-	$(CC) $(ACVP_CFLAGS) $(ACVP_LDFLAGS) $^ $(ACVP_LDLIBS) -o $@
-else
-	@echo "No libacvp header found at $(ACVP_HDR), $(ACVP_APP) is not built"
-endif
+$(XVALID_APP):
+	$(MAKE) -C xvalid-app
 
-$(FUZZ_APP): $(FUZZ_SOURCES)
-ifeq ($(MINGW),0)
-ifneq (, $(shell which clang))
-	clang $(FUZZ_CFLAGS) $(FUZZ_SOURCES) $(LDLIBS) -o $@
-else
-	@echo "Clang is not installed. $(FUZZ_APP) is not built"
-endif
-else
-	@echo "Fuzzing not supported on MinGW build. $(FUZZ_APP) is not built"
-endif
+$(FUZZ_APP):
+	$(MAKE) -C fuzz-app
 
+$(ACVP_APP):
+	$(MAKE) -C acvp-app
+
+$(WYCHEPROOF_APP):
+	$(MAKE) -C wycheproof-app
 
 .PHONY: clean
 clean:
-	-rm -f $(OBJECTS) $(TEST_APP) $(DEP_FILES) $(XVALID_OBJECTS) $(XVALID_APP) $(ASM_OBJECTS) $(FUZZ_APP) $(ACVP_APP)
+	$(MAKE) -C kat-app clean
+	$(MAKE) -C xvalid-app clean
+	$(MAKE) -C fuzz-app clean
+	$(MAKE) -C acvp-app clean
+	$(MAKE) -C wycheproof-app clean
+
+.PHONY: style
+style: clang-format checkpatch
 
 # style check section
 CHECKPATCH?=checkpatch.pl
-CHECKPATCH_FLAGS = --no-tree --no-signoff --emacs --no-color --ignore CODE_INDENT,INITIALISED_STATIC,LEADING_SPACE,SPLIT_STRING,UNSPECIFIED_INT,ARRAY_SIZE,BLOCK_COMMENT_STYLE,GLOBAL_INITIALISERS,AVOID_EXTERNS,COMPLEX_MACRO,USE_FUNC,CONSTANT_COMPARISON,MISSING_SPACE,NEW_TYPEDEFS
+CHECKPATCH_FLAGS = --no-tree --no-signoff --emacs --no-color --max-line-length=100 --ignore CODE_INDENT,INITIALISED_STATIC,LEADING_SPACE,SPLIT_STRING,UNSPECIFIED_INT,ARRAY_SIZE,BLOCK_COMMENT_STYLE,GLOBAL_INITIALISERS,AVOID_EXTERNS,COMPLEX_MACRO,USE_FUNC,CONSTANT_COMPARISON,MISSING_SPACE,NEW_TYPEDEFS
 
-%.c_style_check : %.c
-	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
+ASM_SOURCES := $(wildcard ./**/*.asm) $(wildcard ./**/*.inc)
 
-%.h_style_check : %.h
-	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
+.PHONY: checkpatch
+checkpatch:
+	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $(ASM_SOURCES)
 
-%.asm_style_check : %.asm
-	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
+CLANGFORMAT?=clang-format
+.PHONY: clang-format
+clang-format:
+	@for file in $(wildcard ./*.[ch]) $(wildcard ./**/*.[ch]); do \
+		echo "Checking style $$file"; \
+		$(CLANGFORMAT) -style=file "$$file" | diff "$$file" - | tee /dev/stderr | [ $$(wc -c) -eq 0 ] || \
+		{ echo "ERROR: $$file has style problems"; exit 1; } \
+	done
 
-%.inc_style_check : %.inc
-	$(CHECKPATCH) $(CHECKPATCH_FLAGS) -f $<
+# cppcheck analysis check
+CPPCHECK ?= cppcheck
+CPPCHECK_OPTS ?= -I./ -I../lib
+CPPCHECK_FLAGS ?= -j $(shell getconf _NPROCESSORS_ONLN)
+CPPCHECK_FLAGS1 ?= --cppcheck-build-dir=.cppcheck $(CPPCHECK_FLAGS)
+CPPCHECK_FLAGS2 ?= --cppcheck-build-dir=.bughunt $(CPPCHECK_FLAGS)
+.PHONY: cppcheck
+cppcheck:
+	mkdir -p .cppcheck
+	$(CPPCHECK) --force --enable=all $(CPPCHECK_FLAGS1) $(CPPCHECK_OPTS) \
+		./kat-app ./xvalid-app ./fuzz-app ./acvp-app ./wycheproof-app
 
-SOURCES_ALL := $(wildcard *.[ch]) $(wildcard *.asm) $(wildcard *.inc)
-SOURCES_STYLE := $(foreach infile,$(SOURCES_ALL),$(infile)_style_check)
+.PHONY: bughunt
+bughunt:
+	mkdir -p .bughunt
+	$(CPPCHECK) --bug-hunting --inconclusive $(CPPCHECK_FLAGS2) $(CPPCHECK_OPTS) \
+		./kat-app ./xvalid-app ./fuzz-app ./acvp-app ./wycheproof-app
 
-.PHONY: style
-style: $(SOURCES_STYLE)
-
-# if target not clean or rinse then make dependencies
-ifneq ($(MAKECMDGOALS),clean)
-ifneq ($(MAKECMDGOALS),style)
--include $(wildcard *.d)
-endif
-endif
diff --git a/ceph/src/nvmeof/gateway/spdk/scripts/perf/pm/collect-bmc-pm b/ceph/src/nvmeof/gateway/spdk/scripts/perf/pm/collect-bmc-pm
--- a/ceph/src/nvmeof/gateway/spdk/scripts/perf/pm/collect-bmc-pm
+++ b/ceph/src/nvmeof/gateway/spdk/scripts/perf/pm/collect-bmc-pm
@@ -5,7 +5,13 @@
 
 set -e
 
+pmdir=$(readlink -f "$(dirname "$0")")
+rootdir=$(readlink -f "$pmdir/../../../")
+source "$pmdir/common"
+
 hex() { printf '0x%02x\n' "$@"; }
+
+calc() { bc <<< "scale=2; $*"; }
 
 is_root() {
 	# Talking to local BMC device requires root privileges
@@ -281,12 +287,13 @@ get_dcmi_now_reading() {
 
 		for print in min max avg reading; do
 			[[ -n ${!print} ]] || continue
-			printf '(%s) DCMI %s (mode: %s): %u Watts (interval: %ss)\n' \
+			printf '(%s) DCMI %s (mode: %s): %u Watts (interval: %ss, test: %s)\n' \
 				"$(utc "$ts")" \
 				"$print" \
 				"$mode" \
 				"${!print}" \
-				"$interval"
+				"$interval" \
+				"$TEST_TAG" >&2
 		done
 	fi >&2
 }
@@ -308,11 +315,12 @@ get_sdr_now_reading() {
 			power_readings["${power_sensors[sensor]}"]="_sensor${sensor}_readings[@]"
 			reading+=" $unit"
 		fi < <("$ipmitool" -c -S "$sdr_cache" sdr get "${power_sensors[sensor]}") 2> /dev/null
-		printf '(%s) Sensor %s reading: %s (interval %ss)\n' \
+		printf '(%s) Sensor %s reading: %s (interval: %ss, test: %s)\n' \
 			"$ts" \
 			"${power_sensors[sensor]}" \
 			"$reading" \
-			"$interval" >&2
+			"$interval" \
+			"$TEST_TAG" >&2
 	done
 }
 
@@ -346,16 +354,30 @@ get_cpu_socket_reading() {
 		((${#socket_uj[@]} > 1)) || continue
 
 		# Convert to Watts - use bc since $interval can be an actual float
-		reading=$(bc <<< "scale=2; (${socket_uj[-1]} - ${socket_uj[-2]}) / 1000000 / $interval")
+		reading=$(calc "(${socket_uj[-1]} - ${socket_uj[-2]}) / 1000000 / $interval")
+		if [[ $reading == "-"* ]]; then
+			# Somehow this may happen, probably when the counter wraps over. Consider
+			# this as a faulty reading and don't include it since it may impact overall
+			# avg.
+			printf '(%s) CPU %s %s reading: error(%s) (interval: %ss, test: %s)\n' \
+				"$ts" \
+				"$socket_name" \
+				"$socket_idx" \
+				"$reading" \
+				"$interval" \
+				"$TEST_TAG" >&2
+			return 0
+		fi
 		eval "_socket${_socket_idx}_readings+=($reading)"
 		power_readings["$socket_name-$socket_idx"]="_socket${_socket_idx}_readings[@]"
 
-		printf '(%s) CPU %s %s reading: %s Watts (interval: %ss)\n' \
+		printf '(%s) CPU %s %s reading: %s Watts (interval: %ss, test: %s)\n' \
 			"$ts" \
 			"$socket_name" \
 			"$socket_idx" \
 			"$reading" \
-			"$interval" >&2
+			"$interval" \
+			"$TEST_TAG" >&2
 	done
 }
 
@@ -381,15 +403,16 @@ dump_readings() {
 		fi
 		total=0
 		for reading in "${readings[@]}"; do
-			((total += ${reading%.*}))
+			total=$(calc "$total + $reading")
 		done
-		avg=$((total / ${#readings[@]}))
+		avg=$(calc "$total / ${#readings[@]}")
 
 		readings+=("Total: ${#readings[@]}")
-		printf '%u\n' "$avg" > "$output_dir/${prefix:+${prefix}_}avg_${sensor}.bmc.pm.txt"
-		printf '%s\n' "${readings[@]}" > "$output_dir/${prefix:+${prefix}_}all_${sensor}.bmc.pm.txt"
-		printf 'Dumped avg to %s\n' "$output_dir/${prefix:+${prefix}_}avg_${sensor}.bmc.pm.txt" >&2
-		printf 'Dumped all to %s\n' "$output_dir/${prefix:+${prefix}_}all_${sensor}.bmc.pm.txt" >&2
+		sensor="${sensor//[[:space:]]/_}"
+		printf '%s\n' "$avg" > "$PM_OUTPUTDIR/${prefix:+${prefix}_}avg_${sensor}.bmc.pm.txt"
+		printf '%s\n' "${readings[@]}" > "$PM_OUTPUTDIR/${prefix:+${prefix}_}all_${sensor}.bmc.pm.txt"
+		printf 'Dumped avg to %s\n' "$PM_OUTPUTDIR/${prefix:+${prefix}_}avg_${sensor}.bmc.pm.txt" >&2
+		printf 'Dumped all to %s\n' "$PM_OUTPUTDIR/${prefix:+${prefix}_}all_${sensor}.bmc.pm.txt" >&2
 	done
 }
 
@@ -398,6 +421,7 @@ utc() {
 }
 
 cleanup() {
+	rm_pm_pid
 	[[ -f $sdr_cache && $remove_sdr_cache == yes ]] && rm "$sdr_cache"
 	dump_readings
 }
@@ -418,7 +442,7 @@ collect_readings() {
 help() {
 	cat <<- HELP
 
-		Usage: $0 [-h] [-d dir] [-i sdr|dcmi] [-s SENSOR_NAME] [-t interval] [-l log_file] [-p prefix] [-c count] [-r]
+		Usage: $0 [-h] [-d dir] [-i sdr|dcmi] [-s SENSOR_NAME] [-t interval] [-l] [-p prefix] [-c count] [-r]
 
 		  -h - Print this message.
 		  -d - Directory where the results should be saved. Default is /tmp.
@@ -447,7 +471,6 @@ help() {
 
 is_root
 
-output_dir=/tmp
 interval=1
 remove_sdr_cache=yes
 log_to_file=no
@@ -464,7 +487,7 @@ while getopts :hi:s:d:t:xlp:c:r arg; do
 			help
 			exit 0
 			;;
-		d) output_dir=$OPTARG ;;
+		d) PM_OUTPUTDIR=$OPTARG ;;
 		s) extra_power_sensors+=("$OPTARG") ;;
 		i) interface=${OPTARG,,} ;;
 		t) interval=$OPTARG ;;
@@ -477,16 +500,18 @@ while getopts :hi:s:d:t:xlp:c:r arg; do
 	esac
 done
 
-declare -r sdr_cache=$output_dir/sdr.cache
+declare -r sdr_cache=$PM_OUTPUTDIR/sdr.cache
 declare -r log_file=${prefix:+${prefix}_}${0##*/}.bmc.pm.log
 
-mkdir -p "$output_dir"
+mkdir -p "$PM_OUTPUTDIR"
 if [[ $log_to_file == yes ]]; then
-	printf 'Redirecting to %s\n' "$output_dir/$log_file" >&2
-	exec > "$output_dir/$log_file" 2>&1
+	printf 'Redirecting to %s\n' "$PM_OUTPUTDIR/$log_file" >&2
+	exec > "$PM_OUTPUTDIR/$log_file" 2>&1
 fi
 
+save_pm_pid
 trap 'cleanup' EXIT
+trap 'retag' USR1
 
 ipmi_supported
 power_support
