backport Apache Arrow 15 from tentacle ceph repo
Apache Arrow was basically never updated and we got a ancient version
of 6.5, which breaks compilation due to using c++11, which the abseil
library version from Bookworm doesn't support anymore.

Upstream upgraded it's arrow git submodule [0] in response to compilation
errors for the (future) Ceph 20 Tentacle release, but it's not (yet)
backported to Squid.

As we check in the processed source tarball we cannot just update a
git submodule here, but rather I copied over the src/arrow directory
from ceph tentacle branch.

[0]: https://github.com/ceph/ceph/pull/56585

Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/ceph/src/arrow/dev/tasks/r/github.macos-linux.local.yml b/ceph/src/arrow/dev/tasks/r/github.macos-linux.local.yml
--- a/ceph/src/arrow/dev/tasks/r/github.macos-linux.local.yml
+++ b/ceph/src/arrow/dev/tasks/r/github.macos-linux.local.yml
@@ -15,55 +15,57 @@
 # specific language governing permissions and limitations
 # under the License.
 
-# NOTE: must set "Crossbow" as name to have the badge links working in the
-# github comment reports!
-name: Crossbow
+{% import 'macros.jinja' as macros with context %}
 
-on:
-  push:
-    branches:
-      - "*-github-*"
+{{ macros.github_header() }}
 
 jobs:
-  autobrew:
+  local:
     name: "install from local source"
     runs-on: {{ "${{ matrix.os }}" }}
+  {% if env is defined %}
+    env:
+    {% for key, value in env.items() %}
+      {{ key }}: "{{ value }}"
+    {% endfor %}
+  {% endif %}
     strategy:
       fail-fast: false
       matrix:
         os: [macOS-latest, ubuntu-20.04]
 
     steps:
-      - name: Checkout Arrow
-        run: |
-          git clone --no-checkout {{ arrow.remote }} arrow
-          git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
-          git -C arrow checkout FETCH_HEAD
-          git -C arrow submodule update --init --recursive
-      - name: Configure non-autobrew dependencies (macos)
-        run: |
-          cd arrow/r
-          brew install openssl
+      {{ macros.github_checkout_arrow()|indent }}
+
+      - name: Configure dependencies (macos)
         if: contains(matrix.os, 'macOS')
-      - name: Configure non-autobrew dependencies (linux)
         run: |
-          cd arrow/r
-          sudo apt-get update
-          sudo apt install libcurl4-openssl-dev libssl-dev
+          brew install openssl
+          # disable sccache on macos as it times out for unknown reasons
+          # see GH-33721
+          # brew install sccache
+          # remove cmake so that we can test our cmake downloading abilities
+          brew uninstall cmake
+      - name: Configure dependencies (linux)
         if: contains(matrix.os, 'ubuntu')
-      - uses: r-lib/actions/setup-r@v1
+        run: |
+          sudo env \
+            ARROW_GCS=ON \
+            ARROW_S3=ON \
+            ARROW_SOURCE_HOME=arrow \
+            arrow/ci/scripts/r_install_system_dependencies.sh
+          arrow/ci/scripts/install_sccache.sh unknown-linux-musl /usr/local/bin
+      - uses: r-lib/actions/setup-r@v2
+        with:
+          use-public-rspm: true
       - name: Install dependencies
-        run: |
-          install.packages("remotes")
-          remotes::install_deps("arrow/r", dependencies = TRUE)
-          remotes::install_cran(c("rcmdcheck", "sys", "sessioninfo"))
-        shell: Rscript {0}
-      - name: Session info
-        run: |
-          options(width = 100)
-          pkgs <- installed.packages()[, "Package"]
-          sessioninfo::session_info(pkgs, include_base = TRUE)
-        shell: Rscript {0}
+        uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          cache: false # cache does not work on across branches
+          working-directory: arrow/r
+          extra-packages: |
+            any::rcmdcheck
+            any::sys
       - name: Install
         env:
           _R_CHECK_CRAN_INCOMING_: false
@@ -71,7 +73,10 @@ jobs:
           FORCE_BUNDLED_BUILD: true
           LIBARROW_MINIMAL: false
           ARROW_R_DEV: TRUE
+          LIBARROW_BINARY: false
+        {{ macros.github_set_sccache_envvars()|indent(8)}}
         run: |
+          sccache --start-server || echo 'sccache not found'
           cd arrow/r
           R CMD INSTALL . --install-tests
       - name: Run the tests
