import source of ceph Tentacle 20.2.2
Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/ceph/src/nvmeof/gateway/spdk/test/common/config/pkgdep/git b/ceph/src/nvmeof/gateway/spdk/test/common/config/pkgdep/git
--- a/ceph/src/nvmeof/gateway/spdk/test/common/config/pkgdep/git
+++ b/ceph/src/nvmeof/gateway/spdk/test/common/config/pkgdep/git
@@ -41,18 +41,6 @@ function install_qat() {
 	fi
 }
 
-function install_rocksdb() {
-	# Rocksdb is installed for use with the blobfs tests.
-	if [ ! -d /usr/src/rocksdb ]; then
-		git clone "${GIT_REPO_ROCKSDB}" "$GIT_REPOS/rocksdb"
-		git -C "$GIT_REPOS/rocksdb" checkout 6.15.fb
-		sudo mv "$GIT_REPOS/rocksdb" /usr/src/
-	else
-		sudo git -C /usr/src/rocksdb checkout spdk-v8.1.1
-		echo "rocksdb already in /usr/src. Not checking out again"
-	fi
-}
-
 function install_ittapi() {
 	# Install Intel Instrumentation and Trace API
 	local ittapi_version=v3.24.5 ittapi_dir=/usr/src/ittapi
@@ -128,7 +116,7 @@ function _install_qemu() {
 	declare -a extra_cflags=()
 
 	opt_params+=("--disable-docs")
-	if ((gcc_version >= 9)); then
+	if [[ $CC == *gcc* ]] && ((cc_version >= 9)); then
 		opt_params+=("--disable-glusterfs")
 	fi
 
@@ -231,6 +219,16 @@ function install_libiscsi() {
 	sudo make -C "$GIT_REPOS/libiscsi" install
 }
 
+function install_libblkio() {
+	rm -rf "$GIT_REPOS/libblkio"
+	git clone "${GIT_REPO_LIBBLKIO}" "$GIT_REPOS/libblkio"
+	meson setup "$GIT_REPOS/libblkio/.build" "$GIT_REPOS/libblkio"
+	meson compile -C "$GIT_REPOS/libblkio/.build"
+	meson install -C "$GIT_REPOS/libblkio/.build"
+	echo "/usr/local/lib64" > /etc/ld.so.conf.d/spdk-libblkio.conf
+	ldconfig -X
+}
+
 function install_git() {
 	if type -P git; then
 		if ge "$(git --version | awk '{print $3}')" "$GIT_VERSION"; then
@@ -306,6 +304,50 @@ function install_igb_uio() {
 	sudo mkdir -p "/lib/modules/$(uname -r)/extra/dpdk"
 	sudo cp "$GIT_REPOS/dpdk-kmods/linux/igb_uio/igb_uio.ko" "/lib/modules/$(uname -r)/extra/dpdk"
 	sudo depmod
+}
+
+function install_contigmem() {
+	# Dedicated solely for freebsd
+	[[ $OSID == freebsd ]] || return 0
+
+	rm -rf "$GIT_REPOS/dpdk-stable"
+
+	git clone \
+		--branch "$DPDK_STABLE_BRANCH" \
+		--depth 1 "$DPDK_STABLE_REPO" \
+		"$GIT_REPOS/dpdk-stable"
+
+	# We skip most of the stuff to not waste time during setup but at the very end it won't
+	# matter much as we want to build a single, specific target anyway. Note that DPDK considers
+	# enable_kmods to be deprecated and as such, for freebsd kernel modules are always enabled,
+	# so we don't need to set it in.
+	meson setup \
+		-Ddisable_apps="*" \
+		-Ddisable_libs="*" \
+		-Ddisable_drivers="*/*" \
+		-Dtests=false \
+		"$GIT_REPOS/dpdk-stable/build" \
+		"$GIT_REPOS/dpdk-stable"
+
+	# The thing we are after
+	ninja -C "$GIT_REPOS/dpdk-stable/build" \
+		kernel/freebsd/contigmem.ko
+
+	[[ -e $GIT_REPOS/dpdk-stable/build/kernel/freebsd/contigmem.ko ]] || return 1
+
+	# Put it into one of the default search paths
+	cp -p \
+		"$GIT_REPOS/dpdk-stable/build/kernel/freebsd/contigmem.ko" \
+		"/boot/modules"
+
+	# Make sure kernel loads it early on. Don't put it into the main loader file though, define
+	# custom one. Also, provide a default setup of 2 * 1GB buffers - this should match default
+	# hugepages requirement that autotest enforces under freebsd.
+	cat <<-LOADER >/boot/loader.conf.d/spdk.conf
+		contigmem_load="YES"
+		hw.contigmem.num_buffers="2"
+		hw.contigmem.buffer_size="$((1 << 30))"
+	LOADER
 }
 
 function install_irdma() {
@@ -548,15 +590,16 @@ function install_sources() {
 
 	if [[ $OSID == freebsd ]]; then
 		jobs=$(($(sysctl -n hw.ncpu) * 2))
+		sources+=(install_contigmem)
 	else
 		jobs=$(($(nproc) * 2))
 		sources+=(
 			install_irdma
 			install_libiscsi
+			install_libblkio
 			install_nvmecli
 			install_nvmecli_plugin
 			install_qat
-			install_rocksdb
 			install_qemu
 			install_igb_uio
 			install_ice
@@ -588,9 +631,8 @@ ICE_VERSION=1.14.9
 BPFTRACE_VERSION=${BPFTRACE_VERSION:-f7bdfb44}
 VFIO_QEMU_BRANCH=${VFIO_QEMU_BRANCH:-vfio-user-p3.0}
 VANILLA_QEMU_BRANCH=${VANILLA_QEMU_BRANCH:-v8.0.0}
+DPDK_STABLE_BRANCH=${DPDK_STABLE_BRANCH:-24.11}
 
-: ${GIT_REPO_ROCKSDB=https://review.spdk.io/spdk/rocksdb}
-export GIT_REPO_ROCKSDB
 : ${GIT_REPO_FIO=https://github.com/axboe/fio.git}
 export GIT_REPO_FIO
 : ${GIT_REPO_FLAMEGRAPH=https://github.com/brendangregg/FlameGraph.git}
@@ -601,6 +643,8 @@ export GIT_REPO_QEMU
 export GIT_REPO_QEMU_VFIO
 : ${GIT_REPO_LIBISCSI=https://github.com/sahlberg/libiscsi}
 export GIT_REPO_LIBISCSI
+: ${GIT_REPO_LIBBLKIO=https://gitlab.com/libblkio/libblkio}
+export GIT_REPO_LIBBLKIO
 : ${DRIVER_LOCATION_QAT=https://downloadmirror.intel.com/828487/QAT.L.4.26.0-00008.tar.gz}
 export DRIVER_LOCATION_QAT
 : ${GIT_REPO_GIT=https://github.com/git/git/archive/v${GIT_VERSION}.tar.gz}
@@ -623,10 +667,17 @@ export GIT_REPO_ITTAPI
 export GIT_REPO_DOXYGEN
 : ${GIT_REPO_LIBBPF="https://github.com/libbpf/libbpf"}
 export GIT_REPO_LIBBPF
+: ${DPDK_STABLE_REPO="http://dpdk.org/git/dpdk-stable"}
 
 GIT_REPOS=${GIT_REPOS:-$HOME}
+CC=${CC:-gcc}
 
-gcc_version=$(gcc -dumpversion) gcc_version=${gcc_version%%.*}
+if ! cc_version=$($CC -dumpversion 2> /dev/null); then
+	echo "'$CC' version could not be determined, aborting" >&2
+	return 1
+fi
+
+cc_version=${cc_version%%.*}
 if [[ -e /proc/sys/kernel/osrelease ]]; then
 	kernel_ver=$(< /proc/sys/kernel/osrelease)
 fi
